import json

# TODO: Skis will need to be researched more on for now just loading some of the information needed in order to make it run. Currently the logic will not be able to read or understand what the customer wants.

SKIS = [

    # Blizard (26/27 images)
    
    # Canvas
    {
        "name": "Canvas 100",
        "brand": "Blizzard",
        "styles": ["all-mountain"],
        "skill": ["intermediate", "advanced"],
        "terrain": ["mixed"],
        "local": "",
        "preferences": [],
        "waist_mm": 100,
        "lengths": [162, 168, 174, 180, 186],
        "price": "699.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305172_WHT_1.png?v=1779322250",
        "notes": "This is Canvas 100, a fun-forward ski born from art and created for spontaneity, it transforms terrain into a blank Canvas. This ski was made for expression, not expectation. Jib, butter, pivot and float to your own beat. Because skiing, like art, is most powerful when it’s personal."
    },
    {
        "name": "Canvas 108",
        "brand": "Blizzard",
        "styles": ["all-mountain"],
        "skill": ["intermediate", "advanced"],
        "terrain": ["mixed"],
        "local": "",
        "preferences": [],
        "waist_mm": 108,
        "lengths": [168, 174, 180, 186, 192],
        "price": "799.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305171_WHT_1.png?v=1779321055",
        "notes": "Canvas 108 doesn't dictate the line -- it's for skiers who don't follow tracks -- they paint their own. With topsheets born in an artist’s studio and a shape designed for fun, it's all about the feeling and the expression. You’re the artist—this is your brush."
    },
    {
        "name": "Canvas 118",
        "brand": "Blizzard",
        "styles": ["all-mountain"],
        "skill": ["intermediate", "advanced"],
        "terrain": ["mixed"],
        "local": "",
        "preferences": ['playful', 'powder'],
        "waist_mm": 118,
        "lengths": [172, 180, 186],
        "price": "899.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305170_WHT_1.png?v=1779319612",
        "notes": "Canvas 118 isn’t just a ski—it’s a medium. A place for expression, improvisation, and sending it in ways that make you smile. Playful, light, and open to interpretation, this is the ski for riders who color outside the lines. Clicked into the Canvas there are no rules—just rhythm."
    },
    
    # Rustler
    {
        "name": "Rustler 9",
        "brand": "Blizzard",
        "styles": ["freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": ["mixed"],
        "local": "",
        "preferences": ['powder', 'trees'],
        "waist_mm": 96,
        "lengths": [162, 168, 174, 180, 186],
        "price": "799.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100295443_SDGR_1.png?v=1766785365",
        "notes": "The Rustler 9 is an everyday ski for whatever throws your way. When it’s not blower conditions, this ski is an easy grab. It lights up on chundery, choppy, and icy days. This ski is nimble and predictable, it responds to power with power, and its platform welcomes airs. Don’t hesitate to roll the Rustler 9 up on edge, too, because this ski carves like a dream. Most days aren’t powder days, which means most days are Rustler 9 days."
    },
    {
        "name": "Rustler 10",
        "brand": "Blizzard",
        "styles": ["freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": ["mixed"],
        "local": "",
        "preferences": ['powder', 'trees'],
        "waist_mm": 102,
        "lengths": [162, 168, 174, 180, 186, 192],
        "price": "849.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100295442_BLU_1.png?v=1766781510",
        "notes": "Congrats! You found the freeride ski that nurtures fun. Draw high-speed turns, bounce off bumps, rail chalk, and detonate crud without an ounce of hesitation with the Rustler 10. Then, when the conditions line up, flash straight lines, weasel into snow, send that feature, and throw them sideway for a whiteout! The Rustler 10 is a life-enhancing ski for fun-hogging chargers. This ski oozes tech—like FluxForm and Trueblend—resulting in an underfoot feel that’s equally playful and trustworthy. Mount it now and thank us later."
    },
    
    # Anomaly
    {
        "name": "Anomaly 84",
        "brand": "Blizzard",
        "styles": ["freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": ["mixed"],
        "local": "",
        "preferences": [''],
        "waist_mm": 84,
        "lengths": [164, 170, 176, 182, 188],
        "price": "699.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305175-BLKGRY-5.png?v=1782769069",
        "notes": "This is a ski that mirrors what you put into it. Blizzard's TrueBlend woodcore ensures you don't have to change your style for the Anomaly 84. Instead, this ski is made to make you feel comfortable on snow. The Anomaly 84 will support your style and approach - this ski is fun, pure and simple. "
    },
    {
        "name": "Anomaly 88",
        "brand": "Blizzard",
        "styles": ["freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": ["mixed"],
        "local": "",
        "preferences": [''],
        "waist_mm": 88,
        "lengths": [164, 170, 176, 182, 188],
        "price": "749.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305174-BLUGLD-5.png?v=1782765715",
        "notes": "Are you looking for a ski that helps you level up? You found it! Enter the Anomaly 88. Whether you're piping groomers or bouncing throwing bumps, this is the ski you need. For the unrelenting high-pressure dry spells when snow hasn't fallen for weeks, this ski keeps it fun. Give it a go with this one because the Anomaly 88 will elevate your game. "
    },
    {
        "name": "Anomaly 94",
        "brand": "Blizzard",
        "styles": ["freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": ["mixed"],
        "local": "",
        "preferences": [''],
        "waist_mm": 94,
        "lengths": [164, 170, 176, 182, 188],
        "price": "799.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305173-GRNGLD-4.png?v=1782758776",
        "notes": "Crowded trails, changing terrain, variable snow, and low light are out of your control. But with the Anomaly 94 underfoot you're in control and can take it all in stride. You can gravitate to groomers, play on the side trails, slice zipper lines in trees, or arc in crud without an ounce of hesitation on the Anomaly 94. A higher and more progressive Tip-Tail Rocker profile provide for unparalleled turning capability in all conditions while reimagined camber footprint provides enhanced stability and energy at any speed and in all conditions. "
    },
    
    # Women's Anamoly
    {
        "name": "Women's Black Pearl 84",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Black Pearl 88",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Black Pearl 94",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Sheeva 9",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },

    # ARMADA (26/27 images)
    {
        "name": "ARV",
        "brand": "Armada",
        "styles": ["groomer", "park"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": ['playful'],
        "waist_mm": 94,
        "lengths": [157, 164, 171, 178, 185],
        "price": "649.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306748_1.png?v=1776914439",
        "notes": "All-mountain twin crossover king. The all-mtn twin crossover king, the ARV 94 is the trusty multi-tool with a versatile shape and durable construction. Tip and tail rocker lets it carve, slash and boost in a variety of conditions."
    },
    {
        "name": "ARV",
        "brand": "Armada",
        "styles": ["groomer", "freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 100,
        "lengths": [158, 165, 172, 179, 186],
        "price": "749.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306747_1.png?v=1776911940",
        "notes": "The standard in playful all-mountain versatility. The ARV 100 is a playful, durable all-mountain twin pairing a versatile waist with tip and tail rocker to lap anything from a sneaker pow day to park and frontside laps."
    },
    {
        "name": "ARV",
        "brand": "Armada",
        "styles": ["freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 106,
        "lengths": [164, 172, 180, 188],
        "price": "799.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306746_1.png?v=1776910518",
        "notes": "True one-ski quiver, all-mountain twin. The ARV 106 is the pow to piste all-mountain twin. Plenty of float for deep stashes and stout enough to stomp on with a smooth, round flex that carves, charges, slashes, and butters with ease."
    },
    
    # Women's Armada
    {
        "name": "Women's ARW 84",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's ARW 88",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's AWR 94",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    
    # Nordica (26/27 images)
    {
        "name": "Enforcer",
        "brand": "Nordica",
        "styles": ["groomer", "all-mountain"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 94,
        "lengths": [167, 173, 179, 185, 191],
        "price": "799.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100294730.PetrolGrey.1.png?v=1775604185",
        "notes": "Make each run a masterpiece with Nordica’s Enforcer 94. A favorite among skiers who spend most of their time on trails, this all-mountain ski offers exceptional versatility–and no shortage of confidence. For an outstandingly smooth and stable ride, the Enforcer 94 showcases a fresh construction that embeds both a wood core and an elastomer Pulse core between two layers of titanal. Combined with a versatile waist width, this construction boosts control and response. And thanks to its outstanding edge hold, the Enforcer 94 is at home making powerful and precise turns. Carve your signature all over the mountain with Nordica’s Enforcer 94."
    },
    {
        "name": "Enforcer",
        "brand": "Nordica",
        "styles": ["groomer", "all-mountain"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 99,
        "lengths": [167, 173, 179, 185, 191],
        "price": "849.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100294729.BlueSand.2.png?v=1775597400",
        "notes": "Nordica’s Enforcer 99 embodies everything an all-mountain ski should be–and perfects it. Incredibly playful and versatile, it’s at home in any terrain and all conditions. For an remarkably smooth and powerful ride, the Enforcer 99 features a fresh construction that embeds both a wood core and an elastomer Pulse core between two layers of titanal. Combined with a wider waist, this construction maximizes control and response while also excelling in softer snow. This ski inherits the legendary performance of the Enforcer collection–and then builds upon it to amplify your confidence. Ski everything with ease with Nordica’s Enforcer 99."
    },
    
    # Women's Nordica
    {
        "name": "Women's Santa Ana 87",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Santa Ana 92",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Wild Belle 84 DC + TP2 11",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    # Atomic (26/27 images)
    
    # Bent Chetler
    {
        "name": "Bent Chetler 90",
        "brand": "Atomic",
        "styles": ["park"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 90,
        "lengths": [176, 166, 175, 184],
        "price": "599.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306679-MULTI-5.png?v=1776032908",
        "notes": "The Atomic Bent 90 is the ski Nico and Miguel Porteous refer to as “the Swiss Army knife” – the perfect all-mountain/park ski. HRZN Tech Tip & Tail give the Bent 90 the ability to float through pow laps in the morning and send the park in the afternoon. A Light Woodcore keeps the weight down and the performance responsive. Extra-durable Resist Edges provide lasting durability for endless rail slides. While the Bent 90 is a narrower ski than the bigger Bent Chetler 120, it still maintains the same attitude of creativity, self-expression, and versatility that make the entire range so effective. With topsheet and base art by Chris Benchetler, the Bent 90 channels a unique approach to the mountain both in design and aesthetics."
    },
    {
        "name": "Bent Chetler 100",
        "brand": "Atomic",
        "styles": ["all-mountain", "powder"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 100,
        "lengths": [158, 165, 172, 179, 186],
        "price": "699.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306678-MULTI-5.png?crop=center&height=800&v=1776029087&width=800",
        "notes": "Built for every style from freeride to freestyle, the wildly versatile Atomic Bent 100 is a do-everything ski. Rooted in freeride with a side of all-mountain and a dash of art by Chris Benchetler, the celebrated Bent 100 has been reimagined from tip to tail. Incorporating performance feedback from Atomic athletes, the Bent 100 features a Light Woodcore and Powder Rocker with 5% more rocker for add tail pop and easier transitioning to switch. Freeride specific HRZN 3D delivers improved float in deeper snow and better handling in variable conditions. Dura Cap Sidewalls offer controlled power transmission and commanding edge grip on harder snow and a thicker Resist Edge adds greater durability for sliding park rails. For Bobby Brown it’s a no brainer, the Bent 100 is his everything ski. Playful and sturdy, this is the one that does it all."
    },
    {
        "name": "Bent Chetler 110",
        "brand": "Atomic",
        "styles": ["powder"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 110,
        "lengths": [164, 172, 180, 188],
        "price": "799.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306677-MULTI-5.png?crop=center&height=800&v=1776026129&width=800",
        "notes": "The Atomic Bent 110 takes a similar approach to the mountain as the Bent Chetler 120, with slightly less width. It’s Jossi Wells’s go-to ski for backcountry freestyle, charging lift-served pow laps and days where it’s deep, but not 120-deep. The Bent 110 is designed with HRZN Tech Tip and Tail for a playful performance and better float through blower without adding bulk to the ski. The 110 features a bit less rocker in the tail than the 120 but still charges through variable chop and crud. A Light Woodcore reduces weight and keeps the performance responsive. With topsheet and base art by Chris Benchetler, the Bent 110 is wholly reflective of his approach to the mountains: creative and unique."
    },
    {
        "name": "Bent Chetler 120",
        "brand": "Atomic",
        "styles": ["powder"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": ['powder', 'trees'],
        "waist_mm": 120,
        "lengths": [176, 184, 192],
        "price": "899.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306676-MULTI-5.png?v=1775859210",
        "notes": "One of the most revered freeride skis on the mountain, the Bent Chetler 120 employs next-generation HRZN 3D with a full wrap tip/tail profile for even more playful skiing and better float in the deepest snow. Chris Benchetler’s signature ski and the biggest brother in the Bent family, the latest iteration of the Bent Chetler 120 utilizes Powder Rocker for more float, a poplar Light Woodcore for more strength and a lower-impact design that uses more wood and less metal, fiberglass and resin to decrease the environmental impact of the ski’s production. A wildly imaginative top sheet designed by Chris himself with more recycled material further reduces the overall carbon footprint. In total, material-related CO2 equivalent emissions were cut by 13% (compared with the Bent Chetler 120, 2022). Chris’ favorite update? He’s stoked on the ash wood binding reinforcement band that adds 10% more strength!"
    },
    
    # Maverick
    {
        "name": "Maverick 86 CTI",
        "brand": "Atomic",
        "styles": ["groomer"],
        "skill": ["intermediate", "advanced"],
        "terrain": [""],
        "local": "",
        "preferences": [""],
        "waist_mm": 86,
        "lengths": [153, 159, 165, 172, 179, 186],
        "price": "649.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306675-ONE-3.png?v=1775583840",
        "notes": "The 26/27 Atomic Maverick 86 C is a lighter, more accessible all-mountain ski aimed at advanced intermediates and skiers looking for a forgiving daily driver with real carving ability. It uses a Carbon Backbone construction instead of full CTI for a softer, easier-going feel than its wider brothers. The C in 86 C stands for the Carbon Backbone construction, a lighter and more forgiving build than the full CTI layup found in the rest of the Maverick line. It delivers enough torsional stiffness for good edge hold without the heavy, demanding feel of a full titanal ski. The HRZN 3D tip helps this ski feel planted in variable snow, shedding crud and keeping the ski on track. The rocker profile is more camber-dominant, so you get real carving performance on groomers without the ski feeling too locked in. Dura Cap sidewalls and Dura Edge give you solid durability, and the factory tune is ready to ski out of the shop."
    },
    {
        "name": "Maverick 98 CTI",
        "brand": "Atomic",
        "styles": ["groomer"],
        "skill": ["intermediate", "advanced"],
        "terrain": [""],
        "local": "",
        "preferences": [""],
        "waist_mm": 96,
        "lengths": [165, 172, 179, 186],
        "price": "799.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100306674-ONE-5.png?v=1775578590",
        "notes": "A ski without boundaries, the powerful Atomic Maverick 96 CTI is a wildly versatile all-mountain ski that can handle every slope and snow condition. Smooth and ambitious, the CTI Powered core construction features the perfect mix of carbon and titanal to create the ideal balance of stiffness and flex, delivering improved stability from tip to tail and better snow feel underfoot. Employing All-Mountain Rocker with early rise in the tip for total versatility and a Power Woodcore for added stability and vibration damping at speed, the 96mm waist of the Maverick 96 CTI offers precision performance on hardpack and beyond. The uniquely shaped HRZN 3D tip offers expanded surface area for more float and versatility in powder and variable conditions. Using a unique balance of wood and metal with less fiberglass and resin, the lower-impact design of the Maverick 96 CTI reduces CO2 equivalent emissions by 16%."
    },
    
    # Women's Atomic
    {
        "name": "Women's Maven 84 + M 10 GW",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Maven 86 C",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    
    
    # Rozzy (26/27 images)
    {
        "name": "Sender 100",
        "brand": "Rossignol",
        "styles": ["freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 100,
        "lengths": [162, 170, 178, 184, 190],
        "price": "699.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304821.Sender100.1.png?v=1778615523",
        "notes": "The mountain is your playground. Get creative. The Rossignol Sender Free 100 ski is made for freeride lovers dedicated to seeking out new terrain and sending it everywhere the snow leads them, inbounds and out. This full-sidewall ski combines the exceptional float of a rockered powder ski with the confident grip of an all-mountain board. Twin rocker combined with progressive sidecut supports smears and controlled tail and nose presses in powder. Its lively wood core and lightweight AirTip serve up plenty of pop to inspire your next line."
    },
    {
        "name": "Sender 110",
        "brand": "Rossignol",
        "styles": ["freeride"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [],
        "waist_mm": 110,
        "lengths": [168, 176, 184, 191],
        "price": "899.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304820.Sender110.1.png?v=1778607741",
        "notes": "Explore limitless creativity in any terrain. The Rossignol Sender Free 110 is an athlete-proven ski designed to push the limits of freeriding, from wide open bowls to backcountry kickers and steep lines to the snowpark. This full sidewall ski combines the exceptional float of a powder ski with the confident grip of a big mountain board. Twin rocker profile and Airtip set the bar for fun, responsive skiing, while a PEFC poplar wood core keeps it light and environmentally friendly. Titanal reinforcements and a shock-absorbing VAS construction maintain a predictable, powerful feel in all snow conditions. Made of eco-conscious, bio-sourced resin and a PEFC poplar wood core."
    },
    
    # Women's Rossignol
    {
        "name": "Women's Arcade 78 Xpress 10 GW",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Arcade 80 Xpress 10 GW",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Arcade 82 Xpress 11 GW",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Soul 92 Xpress 11 GW",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },

    # Faction (25/26 Images)
    {
        "name": "Prodigy 2",
        "brand": "Faction",
        "styles": ["park"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": ['playful'],
        "waist_mm": 98,
        "lengths": [159, 165, 171, 177],
        "price": "729.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100403604-ONE-2.png?v=1789761384",
        "notes": "The Prodigy 2 is a timeless fan favorite and best-seller, and for good reason. It is the ultimate all-mountain ski with park DNA, designed to help you pop, stomp, and surf across any terrain. Its poplar core provides the perfect balance of softness and pop for buttering slushy rollers, while maintaining stiffness underfoot with a 98mm waist for serious carving. For this 26/27 model, Faction integrated a carbon/rubber stomp pad to absorb all hits and vibrations, making your ride and creative expression smoother and more sure-footed than ever."
    },
    {
        "name": "Prodigy 1",
        "brand": "Faction",
        "styles": ["park"],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": ['playful'],
        "waist_mm": 88,
        "lengths": [158, 164, 171, 178],
        "price": "629.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100403603-ONE-1.png?v=1789766914",
        "notes": "The Prodigy 1 is designed for skiers seeking precise handling in the park and on-piste. Featuring an award-winning elliptical sidecut, these skis offer effortless turn initiation at any speed, while full strength sidewalls deliver exceptional edge hold. The Prodigy 1 is 88mm underfoot, enhancing its precision on hard-packed features. A unique construction of a poplar wood and ash wood core provides the strength needed to withstand heavy hits. For this 26/27 model, Faction integrated a carbon/rubber stomp pad to absorb vibrations, making your ride and creative expression smoother and more sure-footed than ever. Paired with XL 2.5mm edges, the Prodigy 1 skis are built for lasting durability."
    },
    
    # Women's Faction
    {
        "name": "Prodigy 1 Capsule",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Prodigy 2 Capsule",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    
    # Salomon
    
    # Stance
    {
        "name": "Stance 80 + M11 GW",
        "brand": "Salomon",
        "styles": [""],
        "skill": ["beginner"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 80,
        "lengths": [151, 161, 169, 177],
        "price": "599.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100288688_KLPN_1.png?v=1754107503",
        "notes": "As the slimmest in Salomon's Stance lineup, this Stance 80 setup is all about energy and adaptability, perfect for those who crave adventure beyond the beaten path. Built for versatility and a lively feel at any speed, these skis invite you to explore every corner of the mountain. Get ready to elevate your game and Stance!"
    },
    {
        "name": "Stance 84 R + MI 12",
        "brand": "Salomon",
        "styles": [""],
        "skill": ["beginner"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 84,
        "lengths": [161, 169, 177, 185],
        "price": "799.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305013-AZUREBLUE-6.png?v=1781622282",
        "notes": "Energetic and stable, Salomon's Stance 84 is what you need to ski everywhere on the mountain. The Titanal frame provides the perfect energy for cruising through crud or icy slopes, while a progressive frontside sidecut and poplar wood core deliver lively, controllable turns, no matter how steep or deep the snow."
    },
    
    # Addikt
    {
        "name": "Addikt Pro 76 + MI12 GW",
        "brand": "Salomon",
        "styles": [""],
        "skill": ["beginner"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 84,
        "lengths": [156, 163, 170, 177],
        "price": "949.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100291976-ONE-5.png?v=1781567968",
        "notes": "Built for those who can’t get enough carving, Salomon’s Addikt Pro 76 setup will have you hooked from the first run. With its playful vibe and cutting-edge Motion Tail technology, plus a 76 mm waist that handles both short and long turns like a pro, you'll be charging confidently no matter what the snow’s up to."
    },
    
    # QST
    {
        "name": "QST 94",
        "brand": "Salomon",
        "styles": [""],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 94,
        "lengths": [156, 164, 172],
        "price": "749.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305012-LILACBLK-1.png?v=1781570552",
        "notes": "With a wide tip for softer snow and a 94 mm waist, these skis bridge the gap between All-Mountain and Freeride. Designed for versatile skiers, they offer excellent grip and stability on piste, while providing extra float when needed."
    },
    {
        "name": "QST 94 Black",
        "brand": "Salomon",
        "styles": [""],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 94,
        "lengths": [156, 164, 172],
        "price": "749.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100288684_BLK_1.png?v=1767121434",
        "notes": "With a wide tip for softer snow and a 94 mm waist, these skis bridge the gap between All-Mountain and Freeride. Designed for versatile skiers, they offer excellent grip and stability on piste, while providing extra float when needed."
    },
    {
        "name": "QST 100",
        "brand": "Salomon",
        "styles": [""],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 100,
        "lengths": [148, 156, 164, 172, 180, 188],
        "price": "749.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100288683_CSKY_1.png?v=1767117431",
        "notes": "Meet Salomon's QST 100, the most playful QST ski yet. With a 100 mm waist and dynamic freeride shape, these skis are perfect for your everyday shred. Ideal for carving groomers and exploring powder stashes, they deliver nimble performance and lively responsiveness, setting the perfect vibe for your ride."
    },
    {
        "name": "QST 106",
        "brand": "Salomon",
        "styles": [""],
        "skill": ["intermediate", "advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 106,
        "lengths": [157, 165, 173, 181. 189],
        "price": "849.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100288682_AMLK_1.png?v=1754107513",
        "notes": "Blending the best of the last 4 generations of 106, these QST 106 will be your go-to for all conditions. With a 106mm width and progressive freeride shape, Salomon's QST 106 tackles everything with style and finesse. Perfect for everything from first-chair corduroy to powder shredding, they give you the confidence and agility to own the mountain."
    },
    
    # Women's Salomon
    {
        "name": "Women's Stance 80 + M10 GW",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Stance Pro 82",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Stance 84 + M11 GW",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    # Stockli
    {
        "name": "Stormrider 88",
        "brand": "Stockli",
        "styles": ["all-mountain", "freeride"],
        "skill": ["advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 88,
        "lengths": [169, 174, 179, 184],
        "price": "1549.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100291981_SLV_1.png?v=1767148366",
        "notes": "Whether as a freeride ski or on the slopes, a true all-rounder like the Stormrider 88 knows how to impress everywhere. Rocker technologies from the freeride segment provide excellent lift in fresh snow. The waist width of 88?mm and the sporty tailoring also allow great carving on the slopes. Thanks to slight adjustments to the wood core, it’s now even more playful and agile than ever. So, what are you waiting for? Off to the mountains with you."
    },
    {
        "name": "Stormrider 95",
        "brand": "Stockli",
        "styles": ["all-mountain", "freeride"],
        "skill": ["advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 95,
        "lengths": [170, 176, 182, 188],
        "price": "1,599.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100291980_BLU_1.png?v=1767128498",
        "notes": "The Stormrider 95 really packs a punch and is the perfect choice for freeride and on-piste enthusiasts. Stöckli performance paired with a Powder Rocker and Freeride Tail make the Stormrider 95 a perfect all-mountain freeride ski. The Titec aluminum surface with transparent positive printing not only offers protection, but also gives an attractive aluminum finish."
    },
    {
        "name": "Stormrider 108",
        "brand": "Stockli",
        "styles": [""],
        "skill": ["advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 108,
        "lengths": [174, 180, 186, 192],
        "price": "1,699.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401930-GREEN-1.png?v=1790792774",
        "notes": "The 26/27 Stormrider 108 is Stöckli’s answer to anyone who wants more lift, more stability, and more freedom in deep snow. Developed with freeride pro Maxime Chabloz, every centimeter is packed with professional expertise for demanding runs, high drops, and deep turns. The Big Powder Rocker and Freeride Tail provide massive lift, while the fiberglass-reinforced pre-preg construction makes the ski pleasantly playful. And when things get rough, the double titanium wood core construction remains stable and fully on course."
    },
    {
        "name": "Montero AX with Strive 13D bindings",
        "brand": "Stockli",
        "styles": [""],
        "skill": ["advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 80,
        "lengths": [163, 168, 173, 178],
        "price": "",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401929-BLKYELL-1.png?v=1790724388",
        "notes": "The Montero AX is a versatile ski that feels at home on any terrain and in any conditions, be it on freshly groomed pistes, in fresh snow, or in changeable spring conditions. This ski with All Mountain Rocker ensures lightness and dynamism. The Tip and Tail Flex technology with cut-in aluminum on the tip and tail makes it particularly supple. No matter what awaits you on the piste, the Montero AX ensures harmonious and controlled skiing on any terrain."
    },

    # Women's Stockli
    {
        "name": "Women's Nela 86",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Nela 93",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    
    # K2
    
    # Mindbender Quik
    {
        "name": "Mindbender 85 QuikClik",
        "brand": "K2",
        "styles": [""],
        "skill": ["beginner", "intermediate"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 85,
        "lengths": [156, 163, 170, 177],
        "price": "599.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305266_1.png?v=1776736842",
        "notes": "The Mindbender 85 is an ideal ski for anyone breaking out beyond the groomers. They are lightweight forgiving and intuitive – inspiring confidence in anyone looking to improve their skills on the slopes."
    },
    {
        "name": "Mindbender 90 QuikClik",
        "brand": "K2",
        "styles": [""],
        "skill": ["intermediate"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 90,
        "lengths": [166, 172, 178],
        "price": "699.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305265_1.png?v=1776737319",
        "notes": "Ideal for lighter skiers or those who don’t need the stability and stiffness of a metal laminate ski the Mindbender 90C’s Aspen Micro Block core and All-Terrain Rocker profile will deliver a fun lively ride anywhere on the hill."
    },
    
    # Mindbender
    {
        "name": "Mindbender 88",
        "brand": "K2",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 88,
        "lengths": [164, 170, 176, 182],
        "price": "799.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305264_1.png?v=1776730817",
        "notes": "Hardpack hero with freeride soul. The 88 delivers quick edge-to-edge energy and confidence-inspiring grip. Dark Matter keeps it calm, Titanal I-Beam adds punch. Turn & Burn."
    },
    {
        "name": "Mindbender 96",
        "brand": "K2",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 96,
        "lengths": [168, 173, 178, 183],
        "price": "849.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305263_1.png?v=1776728685",
        "notes": "Precision meets play. The 96 arcs clean on hardpack and dives into trees with confidence. Dark Matter kills chatter, Titanal I-Beam adds backbone, and the shape loves versatility. Anywhere, anytime — this ski is ready."
    },
    {
        "name": "Mindbender 101",
        "brand": "K2",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 101,
        "lengths": [164, 171, 178, 185, 192],
        "price": "899.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305262_1.png?v=1776706048",
        "notes": "Your one-ski quiver for freeride days. From pow stashes to groomer arcs, the Mindbender 101 thrives everywhere. Dark Matter Tech kills chatter for smooth control, while the Titanal I-Beam adds backbone without dead weight. Yep, it goes."
    },
    {
        "name": "Mindbender 111",
        "brand": "K2",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 111,
        "lengths": [1570, 177, 182, 187, 192],
        "price": "899.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305261_1.png?v=1776702399",
        "notes": "Big terrain. Big energy. The 111 is your freeride charger—built for storm days, leftovers, and everything in between. Dark Matter tech kills chatter for smooth control, while Titanal I-Beam adds backbone without dead weight. Point it, pivot it, send it."
    },
    # Women's K2
    {
        "name": "Women's Mindbender 85 Quikclik",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Mindbender 90 Quikclik",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Mindbender 88",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Mindbender 96",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "Women's Mindbender 101",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    
    # Volkl
    {
        "name": "Revolt 101",
        "brand": "Volkl",
        "styles": [""],
        "skill": ["advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 101,
        "lengths": [168, 175, 182, 189],
        "price": "749.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305319-ONE-6.png?v=1781668804",
        "notes": "The one for every day - sporty playful runs with the Revolt 101. The narrower brother of the Revolt 114 is the perfect ski for the first days of the season. Whether it's hard snow, packed powder, or long days on the mountain – the lightweight, high-performance Revolt 101 is aimed at classic skiers as well as seasoned freestylers and former racers with freeski ambitions who are looking for a lively all-mountain ski that feels at home in various conditions. The Revolt 101 wants to be ridden sportily on the piste and performs directly on the edge, but also impresses in tree runs off-piste. Although switch riding is possible, the ski is not a typical twin-tip but rather directional. The proven Völkl 3D sidecut ensures outstanding agility and allows for the tightest turns. The flat tail further emphasizes the ski's forward-oriented character, positively affecting carving properties on and off the piste and helping to reduce speed. "
    },
    {
        "name": "Mantra 84",
        "brand": "Volkl",
        "styles": [""],
        "skill": ["advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 84,
        "lengths": [163, 170, 177, 184],
        "price": "749.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305318-ONE-1.png?v=1781629150",
        "notes": "The 2027 Volkl Mantra 84 is a precision-focused frontside ski built for skiers who crave powerful carving performance and unwavering confidence on firm snow. Its 3D Radius Sidecut, Multilayer Woodcore, and full sidewall construction work together to deliver exceptional edge grip, smooth turn transitions, and remarkable stability at speed. While it thrives on groomers, the Mantra 84 remains composed in mixed conditions, making it a versatile choice for advanced skiers who value accuracy and control."
    },
    {
        "name": "Mantra 88",
        "brand": "Volkl",
        "styles": [""],
        "skill": ["advanced"],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 88,
        "lengths": [163, 170, 177, 184],
        "price": "849.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305317-ONE-6.png?v=1781633316",
        "notes": "Whatever your style of descent – piste or terrain – the Mantra 88 can do it. With the redesigned Mantra 88, Völkl offers a medium waist-width model with modern features, that hits the core of current demands for maximum versatility on and off piste as well as powerful turns in all snow conditions. Redefined during the redesign, the Mantra 88 comes with innovative Völkl technologies that now provide more dynamics, pop and accessibility. Among other things, the fibers of the Tailored Carbon Tips have been repositioned for improved agility and dynamics. Adapted as well are the radii of the 3D Radius Sidecut, underlining the flexibility of the technology. The underfoot radius of the Mantra 88 has been shortened by a meter for enhanced turn variety. The updates culminate in a ski with efficient power transmission and a sporty riding style that provides full control and more maneuverability on groomed slopes and in challenging terrain. "
    },
    {
        "name": "Peregrine 82 Lowride + LR 13 FR",
        "brand": "Volkl",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 82,
        "lengths": [162, 167, 172, 177, 182],
        "price": "1199.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100305321-ONE-6.png?v=1781638848",
        "notes": "With the Peregrine 82, Völkl has developed a model that at 82 mm underfoot meets skiers ever changing needs without neglecting the fun of skiing: more stable and resistant to the ever changing conditions, making skiing in the resort effortless and easier to turn. The Peregrine 82 excels on both icy slopes and fresh snow, delighting experienced skiers with its performance. Thanks to the unique Völkl Tailored Carbon Tips the ski provides more agility for quick short turns in changing conditions. In addition, the 3D Radius Sidecut supports the versatility for a playful skiing. The combination of the new tip geometry plus the integrated Tailored Titanal Frame results in a more direct, precise & reliable handling with highest stability. Marker and Völkl teamed up to construct the specific LowRide XL binding with GripWalk which allows great power transfer and edge grip due to the extra low stand height."
    },
    
    # Elan
    {
        "name": "Ripstick 88",
        "brand": "Elan",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 88,
        "lengths": [161, 168, 175, 182],
        "price": "749.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401831_1.png?v=1788963917",
        "notes": "Experience seamless transitions from turn to turn as you explore the mountain in confidence and control as these skis adapt effortlessly to changing conditions. With unparalleled edge grip and precise handling on groomed terrain, the Ripstick 88 remains smooth and agile in mixed snow conditions. With just enough width, the skis rise to the occasion when the snow stacks up and effortlessly floats through powder."
    },
    {
        "name": "Ripstick 96",
        "brand": "Elan",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 96,
        "lengths": [161, 168, 175, 182, 189],
        "price": "799.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401829_1.png?v=1788908271",
        "notes": "The Ripstick 96 strikes the perfect balance between being a powder aficionado and a groomer champion. It redefines the all-mountain skiing experience with unparalleled versatility by excelling both on and off trail, gaining the immediate trust of skiers in all conditions. It’s agile and light to maneuver effortlessly through tight trees, floats in fresh powder and maintains all the edge grip and control you need for laying down arcs on groomers. The best part? You can ski all day thanks to its lightweight construction, minimizing fatigue to maximize your time on the slopes."
    },
    {
        "name": "Ripstick 102",
        "brand": "Elan",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 102,
        "lengths": [161, 168, 175, 182, 189],
        "price": "849.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401828_1.png?v=1788901063",
        "notes": "From epic pow days to hot laps at the resort, this ski is equipped to handle anything nature throws your way. Engineered to do to the unimaginable; be a lightweight ski with a powerfully smooth ride that responds effortlessly in all conditions and terrain. It's Tubelight woodcore enhanced with carbon rods, UD carbon and flax fiber tips are perfect for skiers who demand a mix of floatation in powder, agility in technical terrain and stability on groomed runs when the powder stash runs low."
    },
    {
        "name": "Ripstick 88 Black Edition",
        "brand": "Elan",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 88,
        "lengths": [4154, 161, 168, 175, 182, 189],
        "price": "899.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401832_1.png?v=1788964640",
        "notes": "The most requested addition to the Ripstick Black Edition family, the 88 is designed to satisfy skiers who encounter firm snow and typical front side of the resort conditions. Built with the same carbon DNA as it's siblings, the Ripstick 88 Black Edition excels at carving on trail and delivers a smooth, grippy feel in a lightweight package thanks to additional carbon, but still has enough width to shine when snow starts to pile up."
    },
    {
        "name": "Ripstick 96 Black Edition",
        "brand": "Elan",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 96,
        "lengths": [161, 168, 175, 182, 189],
        "price": "949.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401830_1.png?v=1788908634",
        "notes": "Crafted to strike the perfect balance between on-trail precision and off-trail exploration, these skis excel with added muscle and a super smooth feel from the Black Edition formula. Lightweight yet powerful, these skis deliver agility and control without compromise. Featuring a sleek, timeless all-black design infused with added carbon to ensure you stand out with distinction whether on groomed snow or mixed conditions. Made for skiers with top shelf taste in style who demand excellence every day of the season."
    },
    
    # Womens Elan
    {
        "name": "Women's Ripstick 88",
        "brand": "Elan",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 88,
        "lengths": [147, 154, 161, 168, 175],
        "price": "699.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401834_1.png?v=1788902817",
        "notes": "Experience seamless transitions from turn to turn as you explore the mountain in confidence and control as these skis adapt effortlessly to changing conditions. With unparalleled edge grip and precise handling on groomed terrain, the Ripstick 88 remains smooth and agile in mixed snow conditions. With just enough width, the skis rise to the occasion when the snow stacks up and effortlessly floats through powder."
    },
    {
        "name": "Women's Ripstick 94",
        "brand": "Elan",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": 94,
        "lengths": [147, 154, 161, 168, 175],
        "price": "749.99",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100401833_1.png?v=1788901896",
        "notes": "The beloved Ripstick 94W is the queen of the mountain poised to take on any condition from manicured groomers to slushy bumps to surprise pow days. It redefines skiing anywhere at the resort with unparalleled versatility, excelling both on and off trail. The best part? You can ski all day thanks to its especially lightweight Tubelite woodcore construction, minimizing fatigue and maximizing time on the slopes."
    },
    
    
    # EXTRA
    {
        "name": "",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
    {
        "name": "",
        "brand": "",
        "styles": [""],
        "skill": [""],
        "terrain": [],
        "local": "",
        "preferences": [''],
        "waist_mm": ,
        "lengths": [],
        "price": "",
        "image": "",
        "notes": ""
    },
]
