import json

"""
    {
        "name": "",
        "brand": "",
        "styles": [""],
        "flex": ,
        "sizes": [],
        "lacing": [],
        "price": "",
        "image": "",
        "notes": "",
    },
"""
# I think for now just copy the notes that the website has gather a couple notes on the boots in store then change from there.

BOOTS = [
    # Ride
    {
        "name": "Lasso",
        "brand": "Ride",
        "styles": ["all-mountain"],
        "flex": 7,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14, 15],
        "lacing": ["double-boa"],
        "price": "379.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303347_BLK_1.png?crop=center&height=800&v=1778544478&width=800"
        "notes": "This boot showed the most dominance in 25/26 season being nearly impossible to keep in stock. This boot secures the heel      ensuring maximum control. This boots lacing mechanism really allows the boots to get tight with their new H5 boa for the 26/27  season where the previous season the B.O.A can only tighten where as of now can really perfect the fit without loosening the whole dial. (Only front lace, not heel lace). This boot also offers calf adjustment for those larger calfs. This boot is meant for anyone from narrow to wide."
    },
    {
        "name": "Anthem",
        "brand": "Ride",
        "styles": ["all-mountain"],
        "flex": 3,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14, 15],
        "lacing": ["single-boa"],
        "price": "289.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303348_BLK_1.png?crop=center&height=800&v=1778545677&width=800",
        "notes": "This is the cheaper alternative single B.O.A for someone who is either looking for a really soft boot. This boot is great for beginners that are looking for something to get into the sport."
    },
    {
        "name": "Lasso Pro",
        "brand": "Ride",
        "styles": ["all-mountain", "freeride"],
        "flex": 8,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14, 15],
        "lacing": ["double-boa"],
        "price": "459.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303345_BLK_1.png?crop=center&height=800&v=1778277477&width=800",
        "notes": "You might wonder why the Lasso Pro, well it comes with H5 B.O.A dials for both dials compared to the Lasso. This boot comes with a powder skirt for those deep days, Michelin sole for traction, burrito wrap liner compared to the lace liner in the Lasso. This boot is a stiffer boot that allows responsive ride feeling with a wide option as well."
    },
    {
        "name": "Deadbolt Zonal",
        "brand": "Ride",
        "styles": ["all-mountain"],
        "flex": 7,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14, 15],
        "lacing": ["double-boa"],
        "price": "409.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303346_BLK_1.png?crop=center&height=800&v=1778543319&width=800",
        "notes": "The Deadbolt Zonal is packed with technology to make your life on-hill a tad easier, like an Intuition™ Support Foam Liner, a BOA® Zonal Fit System for extra hold and a liner integrated Tongue Tied™ Hybrid Harness, where the liner lace pull closes the liner harness and Tongue Tied™ system assuring an optimal fit. The Impact Rubber Cup Sole with Ride Fusion Rubber uses recycled premium rubber and Eco +Slime Midsole for traction and cushioning. The Deadbolt is a responsive all-mountain freestyle boot that combines comfort and support while allowing you to focus on what matters most, and that’s progressing your riding."
    },
    {
        "name": "Insano",
        "brand": "Ride",
        "styles": ["all-mountain"],
        "flex": 10,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14, 15],
        "lacing": ["double-boa"],
        "price": "489.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303343_BLK_1.png?crop=center&height=800&v=1778275313&width=800",
        "notes": "Insano. Ask anyone who works in a snowboard shop about it. This is the boot that doesn’t mess around. The snowboard boot built for stability and performance to handle every condition. Fitted with RIDE’s Intuition™ Center Tongue Dream Liner for a supportive and customizable fit. BOA® Closer Wrap is a dial activated fit system that wraps over the midfoot of the foot for a more even closure to reduce pressure points, increase fit and provide better heel hold. The Insano also features the updated Flex Slime Tongue™ for better rebound and damping. The Michelin® Hybrid Traverse Outsole emphasizes grip and response underfoot. The Insano is the stiffest boot in the RIDE line by design, this thing is built for all-mountain response all the time."
    },

    # K2
    {
        "name": "Maysis",
        "brand": "K2",
        "styles": ["all-mountain"],
        "flex": 7,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["double-boa"],
        "price": "379.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303471_BLK_1.png?v=1775852175",
        "notes": "K2 re-designed the Maysis to perform like a workhorse and fit like a glove, and its feature-forward design has it ranked as a perennial bestseller. It starts with a heat-moldable liner made of open-cell Intuition™ foam - allowing the liner to form to the exact shape of your leg, ankle, and foot for superior fit, warmth, and comfort. The secret to the award-winning fit is the Conda™ liner lacing system. Powered by a BOA® Fit System dial, this forgiving and adjustable harness is designed to pull the user's heel into the boot's heel pocket. This urethane-based harness hugs your ankle and flexes naturally. A high-powered BOA® Fit System H5 Coiler closes the shell securely and can be done without removing your gloves. Lastly, to add durability and maintain the boot's flex over the boot's lifetime, they constructed the K2 Maysis using Endo™ 3.0 technology. Underfoot, they've used premium materials to improve damping and grip. The outsole is built using proprietary This Grips!™ dual-rubber compound to provide excellent grip both on and off the snow. This is all set atop a dual-density midsole comprised of a lightweight EVA and our proprietary Harshmellow™, designed to dampen vibration on rough terrain and cushion big landings."
    },
    {
        "name": "Theory",
        "brand": "K2",
        "styles": ["all-mountain"],
        "flex": 7,
        "sizes": [6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13],
        "lacing": ["double-boa"],
        "price": "409.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303465_BLK_1.png?v=1775850369",
        "notes": "Ok, here’s the deal. K2 wanted a boot that could keep up with the demands of modern snowboarding. Something packed with tech, loaded with performance, and clean enough to look good doing it. So, they did just that. The K2 Theory introduces F.O.R.M. (“Fit Optimization for Ride and Mobility”) Wrap Solution, an innovative three-panel design that wraps seamlessly from the medial to lateral side of your foot for a true custom fit. Powered by dual H5 BOA® dials, the upper shell tightens and actively draws your heel into the pocket, maximizing response while eliminating heel lift. Inside, the Intuition™ Control Foam 3D Wrap Liner brings a heat-moldable, dual-density foam that shapes perfectly for a fit that’s dialed, warm, and supremely comfortable. Add in the 3-Point Internal Harness, and you’ve got a locked-in feel that moves with you from first chair to final lap. Responsive and powerful when you're charging but forgiving enough to stay playful, the Vibram® V5 Outsole with Harshmellow™ damping eats up impact, grips icy boot packs, and keeps things feeling smooth. A reinforced rubber toe cap rounds things out for added durability and wet-weather defense."
    },
    {
        "name": "Orton",
        "brand": "K2",
        "styles": ["all-mountain"],
        "flex": 8,
        "sizes": [8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["double-boa"],
        "price": "489.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303464_BLK_1.png?v=1775848403",
        "notes": "It started with an idea. K2 snowboard boot scientists approached Team Rider Sage Kotsenburg with a new concept on snowboard boot construction - and the switch flipped, it was on. A first-of-it’s-kind construction comes from a one-piece rubber lower with integrated mesh. To boil it down, this means that the Orton will not only be waterproof, but also warm and dry, all day long. The one-piece-rubber lower is married with a dual-zone BOA® Fit System, making this a versatile boot, fitting feet of all shapes and sizes. Thousands and thousands of hours went into setting a new standard with the Orton. Sage knows that the devil is in the details… and he’s detailed. For the best performance in the bootpack, K2 chose a Vibram® V5 rubber outside. For ultimate damping and vibration absorption, they chose an Eco-Harshmellow™ injected midsole and Eco-Harshmellow™ Pro insole. For the best possible fit, a performance liner-lasting and a heat moldable, tri-density, Intuition™ Pro Foam 3D Liner. To top it all off, a rip-stop asym lace-cover with a gaiter hook keeps all the snow out."
    },
    {
        "name": "Raider",
        "brand": "K2",
        "styles": ["all-mountain"],
        "flex": 4,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["single-boa"],
        "price": "279.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303468_GRY_1.png?v=1775856349",
        "notes": "With upgraded fit and functionality comes progression, and that’s precisely what K2 had in mind when they designed the Raider snowboard boot. A long-time favorite of resort employees and progressing snowboarders alike, K2 packed all the essentials into the mix in the Raider, starting with an H5 Coiler BOA® Fit System. This securely closes the shell using a stainless-steel BOA® lace for the perfect fit and helps to effortlessly get you in and out of your boots at the beginning and end of the day. Next, K2 added Fast-In liner lacing to maximize fit and keep the liner snug against the contours of your feet. No matter the shape of your foot, the ultra-warm, heat-moldable, and breathable Intuition™ Comfort Foam 3D liner hugs every nook and cranny for a great fit right out of the box. K2 added internal and external J-bars to the liner to increase responsiveness when turning, wrapping your ankles with support and cushion, and added an EVA footbed for comfort."
    },

    # Salomon
    {
        "name": "Dialogue",
        "brand": "Salomon",
        "styles": ["all-mountain"],
        "flex": 6,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 12.5],
        "lacing": ["double-boa"],
        "price": "429.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303316_BLK_1.png?v=1779123852",
        "notes": "The Dialogue Dual BOA® features a precise fit and progressive flex focused on freestyle performance. This mid-flexing boot features zonal customization and a Precision Harness™ 3.0, securing your heel to provide an articulated fit. Built with FTR construction, the Dialogue offers a light and durable design with superior grip and dampening underfoot."
    },
    {
        "name": "Faction",
        "brand": "Salomon",
        "styles": ["all-mountain"],
        "flex": 2,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["double-boa"],
        "price": "279.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303320_BLK_1.png?v=1779130003",
        "notes": "The Faction BOA® brings everyday performance and a first-rate fit for those looking to progress. Inspired by Salomon footwear DNA, this boot combines durability and comfort in a lightweight design with a Feather 1.0 outsole, offering shock absorption and grip, and a heat moldable liner. Dial it all in with BOA® Fit System for a secure fit."
    },
    {
        "name": "Dialogue Lace",
        "brand": "Salomon",
        "styles": ["all-mountain"],
        "flex": 5,
        "sizes": [9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["lace"],
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303318_RED_1.png?v=1779124475",
        "notes": "The Dialogue Lace SJ BOA® features a precise fit and progressive flex focused on freestyle performance. This mid-flexing boot features BOA® Fit System’s STR8JKT harness, securing your heel to provide a comfortable, articulated fit. Built with FTR construction, this boot offers a light and durable design with superior grip and dampening underfoot."
    },
    {
        "name": "X Approach Lace",
        "brand": "Salomon",
        "styles": ["all-mountain"],
        "flex": 4,
        "sizes": [8, 8.5, 9, 9.5, 10, 10.5, 11],
        "lacing": ["lace"],
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303316_BLK_1.png?v=1779123852",
        "notes": "The X Approach Lace SJ BOA® is a unisex park and freestyle boot inspired by iconic Salomon footwear DNA. Utilizing premium materials and Fit To Ride construction, the X Approach offers superior comfort in a lightweight design along with BOA® activated STR8JKT, eliminating heel-lift for enhanced support."
    },
    
    # Union
    {
        "name": "Reset Pro",
        "brand": "Union",
        "styles": ["all-mountain"],
        "flex": 8,
        "sizes": [8, 8.5, 9, 9.5, 10, 10.5, 11],
        "lacing": ["double-boa"],
        "price": "649.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303383.Black.3.png?v=1780435792",
        "notes": "The Union Reset Pro is built for riders who demand uncompromising precision and control. Featuring Union’s patented Single Frame Shell, a powerful BOA® Fit System, and a rugged Vibram® outsole, it delivers pro-level response and durability in all conditions. Purpose-built for snowboarders at the highest level, the Reset Pro sets the new standard in boot performance."
    },
    {
        "name": "Reset",
        "brand": "Union",
        "styles": ["all-mountain"],
        "flex": 7,
        "sizes": [8, 8.5, 9, 9.5, 10, 10.5, 11],
        "lacing": ["double-boa"],
        "price": "549.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303384.Black.1.png?v=1780441049",
        "notes": "The Union Reset is built for riders who want premium performance with zero break-in time. Featuring Union’s patented Single Frame Shell™ and a secure BOA® Fit System, it delivers unmatched out-of-the-box comfort and all-mountain capability. Responsive yet forgiving, the Reset strikes the perfect balance of support and ease for snowboarders who ride it all."
    },
    
    # Burton
    {
        "name": "Highshot X Pro Step On",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 8,
        "sizes": [8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["step-on", "triple-boa"],
        "price": "729.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304047_BLK_1.png?v=1781887899",
        "notes": "The Highshot X Pro Step On® is built for riders who go hard and want even more out of every run. A firm, responsive flex delivers instant edge response: when you move, the board moves with you. Three-zone BOA® control at the upper cuff, ankle, and forefoot lets you fine-tune the fit with precision, locking your heel down and giving you unmatched board control. And with Step On®, the moment you reach the top, you’re stepping in and dropping.",
    },
    {
        "name": "Ion BOA",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 7,
        "sizes": [8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["double-boa"],
        "price": "689.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100218742-BLK-2.png?v=1740083082",
        "notes": "Season after season, the Ion sets the bar for responsive feel and out-of-the-box fit. The men's Burton Ion BOA® Snowboard Boots take it one step further with high-power micro-adjustable tensioning for the upper and lower boot. Combined with a firm flex, they support full-speed-ahead charging for riders who like to rip. Warm, dry feet and unmatched control for dropping lines and sticking landings are all yours.",
    },
    {
        "name": "Highshot X Step On",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 6,
        "sizes": [6, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14],
        "wide_sizes": [8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12]
        "lacing": ["double-boa", "step-on"],
        "price": "529.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304048_BLK_1.png?v=1781890681",
        "notes": "Made for those who like a responsive, powerful boot, the men's Burton Highshot X Step On® Snowboard Boots give you total control of boot fit and tensioning to match its powerful flex. A Dual-Zone BOA® Fit System lets you independently adjust the upper and lower boot tension, including an internal ankle hammock, for the ultimate in micro-adjustable fit and feel. Add out-of-the-box comfort, and we're talking about a true step-on-and-go program for riders who like to rip.",
    },
    {
        "name": "Highshot Plus Step On",
        "brand": "Brand",
        "styles": ["all-mountain"],
        "flex": 4,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14, 15],
        "lacing": ["double-boa" "step-on"],
        "price": "449.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304050_BKWH_1.png?v=1781891750",
        "notes": "An innovative design made for those who like a responsive, powerful boot. The men's Burton Highshot Step On Snowboard Boots give you total control of boot fit and tension to match its powerful flex. The Dual Zone BOA® Fit System lets you adjust the upper and lower boot tension independently for a custom feel. Add out-of-the-box comfort of the wrap liner, and we're talking about a true step-on-and-go program for riders who like to rip.",
    },
    {
        "name": "Ruler",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 5,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["double-boa"],
        "price": "359.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304057_WHT_1.png?v=1781898002",
        "notes": "With a legacy of pushing personal skills to the pro level, the men's Burton Ruler Snowboard Boots are the choice for stepping to larger drops, hitting burlier features, and pushing your skills. The ability to independently dial in the tension between the upper and forefoot lets you fine tune the fit and feel to match your ambitions. Their proven formula creates a medium stiff, responsive feel that's equally nimble and powerful. Warm feet and a custom fit keep you riding longer and thinking about your feet less.",
    },
    {
        "name": "Highshot Step On",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 4,
        "sizes": [6, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14],
        "lacing": ["single-boa", "step-on"],
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100286237_BLK_1.png?v=1749593129",
        "notes": "Made for those who like a responsive, powerful boot, the men's Burton Highshot Step On® Snowboard Boots give you total control of boot fit and tensioning to match its powerful flex. A Sequence BOA® Fit System lets you control the shell closure and tension around your foot with a single dial. Add out-of-the-box comfort, and we're talking about a true step-on-and-go program for riders who like to rip.",
    },
    {
        "name": "Moto",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 2,
        "sizes": [6, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14, 15],
        "lacing": ["single-boa"],
        "price": "279.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100170048_BLK_1.png?v=1743631416",
        "notes": "Slide right past the break-in period with the Burton Moto BOA® Snowboard Boots. We are talking warm and comfortable right out of the box. Add lightweight liners that prioritize warm, dry feet and you'll be able to ride longer. The effortless micro-adjustability BOA® Fit System means a connected feel and no wasted time, while an ultralight outsole cushions every landing no matter how cold it gets.",
    },
    
    # Womens Burton
    {
        "name": "Women's Highshot X Pro Step On",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 7,
        "sizes": [6, 6.5, 7, 7.5, 8, 8.5, 9],
        "lacing": ["triple-boa", "step-on"],
        "price": "729.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304052_BLK_1.png?v=1781889741",
        "notes": "The Highshot X Pro Step On® is built for riders who go hard and want even more out of every run. A firm, responsive flex delivers instant edge response: when you move, the board moves with you. Three-zone BOA® control at the upper cuff, ankle, and forefoot lets you fine-tune the fit with precision, locking your heel down and giving you unmatched board control. And with Step On®, the moment you reach the top, you’re stepping in and dropping.",
    },
    {
        "name": "Women's Highshot X Step On",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 6,
        "sizes": [5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10],
        "lacing": ["double-boa", "step-on"],
        "price": "529.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304053_BLK_1.png?v=1781892758",
        "notes": "Made for those who like a responsive, powerful boot, the women's Burton Highshot X Step On® Snowboard Boots give you total control of boot fit and tensioning to match its powerful flex. A Dual-Zone BOA® Fit System lets you independently adjust the upper and lower boot tension, including an internal ankle hammock, for the ultimate in micro-adjustable fit and feel. Add out-of-the-box comfort, and we're talking about a true step-on-and-go program for riders who like to rip.",
    },
    {
        "name": "Women's Felix BOA",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 5,
        "sizes": [5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5],
        "lacing": ["double-boa"],
        "price": "479.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304058_NPRP_1.png?v=1782152050",
        "notes": "The only thing you need to worry about when you're riding in the women's Burton Felix BOA® Snowboard Boots is what run to hit next. They're packed with the tech to keep you warm and dry, plus a micro-adjustable fit that locks in a secure hold and lets you dial in the feel of the upper and lower to match your feet. And it's all packed into a responsive flex that encourages a relaxed stance and all-terrain versatility.",
    },
    {
        "name": "Women's Highshot Plus Step On",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 5,
        "sizes": [5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10],
        "lacing": ["double-boa", "step-on"],
        "price": "449.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304054_BLK_1.png?v=1781893525",
        "notes": "An innovative design made for those who like a responsive, powerful boot. The men's Burton Highshot Step On Snowboard Boots give you total control of boot fit and tension to match its powerful flex. The Dual Zone BOA® Fit System lets you adjust the upper and lower boot tension independently for a custom feel. Add out-of-the-box comfort of the wrap liner, and we're talking about a true step-on-and-go program for riders who like to rip.",
    },
    {
        "name": "Women's Highshot Step On",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 3,
        "sizes": [5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10],
        "lacing": ["single-boa"],
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304055_BLK_1.png?v=1781894411",
        "notes": "Made for those who like a responsive, powerful boot, the women's Burton Highshot Step On® Snowboard Boots give you total control of boot fit and tensioning to match its powerful flex. A Sequence BOA® Fit System lets you control the shell closure and tension around your foot with a single dial. Add out-of-the-box comfort, and we're talking about a true step-on-and-go program for riders who like to rip.",
    },
    {
        "name": "Women's Mint BOA",
        "brand": "Burton",
        "styles": ["all-mountain"],
        "flex": 2,
        "sizes": [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10],
        "lacing": ["single-boa"],
        "price": "279.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100170047_BLK_1.png?v=1743630947",
        "notes": "Soft, forgiving, and quick to adjust, the Burton Mint BOA® boots are ready for progression right out of the box. Effortlessly fine tune fit tension with the micro-adjustable BOA® Fit System, and cradle your feet in the lightweight cushioning of a DynoLITE outsole. The Mint's relaxed ride is matched by the added warmth of heat-reflective tech that seals in body heat to keep your toes warm and the custom feel of heat-moldable liners.",
    },
    
    # Vans
    {
        "name": "Men's Infuse",
        "brand": "Vans",
        "styles": ["all-mountain", "freeride", "park"],
        "flex": 7,
        "sizes": [7, 7.5, 8, ],
        "lacing": ["single-boa-lace"],
        "price": "420.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100403421-CUMMINBLU-2.png?v=1790181939",
        "notes": "The Infuse is about performance, plain and simple. As one of Vans most popular all-terrain, all-condition boots, it's loaded with top-shelf features like the Vans Flex Control System for control, Powercuff Strap for stability, a V3 Popcush Footbed for anatomical foot support, and a Hybrid Plus BOA Custom Fit System for quick adjustments anywhere you go. This boot has everything you want in a snowboard boot. The question is: what are you gonna do with it?",
    },
    {
        "name": "Men's Invado OG",
        "brand": "Vans",
        "styles": ["all-mountain", "park"],
        "flex": 4,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13],
        "lacing": ["single-boa-lace"],
        "price": "235.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100278871-BLKWHT-3.png?v=1727895298",
        "notes": "The Invado OG combines a Vans classic look with the solution to an age-old snowboarding problem—the lack of a decent heel hold. The Vans Hybrid BOA Fit System merges traditional lacing and the power of a BOA closure at the instep with the Custom Slide Guide to provide targeted and instantly customizable heel hold in any terrain or situation. This makes the Invado OG an easy choice for any rider looking for style and performance at an incredible value.",
    },
    {
        "name": "Men's Aura Pro 2.0",
        "brand": "Vans",
        "styles": ["freeride", "all-mountain"],
        "flex": 5,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13],
        "lacing": ["double-boa"],
        "price": "330.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100403419-BLKWHT-1.png?v=1790177782",
        "notes": "The Aura Pro 2.0 brings a fresh, modern look to one of Vans most versatile all-mountain boots. With a slightly stiffer flex and a fit that stays supportive from first chair to last, it’s built for riders who want dependable control without giving up comfort. The dual-zone BOA® Fit System makes micro-adjustments quick and easy, while the inside delivers warmth and cushioning for long days on snow. Style, comfort, and all-around performance—this updated design delivers it all.",
    },
    
    # Women's Vans
    {
        "name": "Women's Encore Pro 2.0",
        "brand": "Vans",
        "styles": ["freeride", "all-mountain"],
        "flex": 5,
        "sizes": [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 11],
        "lacing": ["double-boa"],
        "price": "310.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100403424.PortRoyale.1.png?v=1790613432",
        "notes": "The Encore Pro 2.0 brings new energy to one of Van's most trusted women’s boots. With refined lines, an updated flex profile, and a dialed-in fit, it delivers the comfort and control riders rely on from first chair to last. The dual-zone BOA® Fit System tightens quickly and evenly, while the inside packs in the warmth and cushioning needed for full days on the mountain. Dependable, responsive, and easy to ride—this is why the Encore Pro has been a cornerstone in the line for years.",
    },
    {
        "name": "Women's Encore OG",
        "brand": "Vans",
        "styles": ["park", "all-mountain"],
        "flex": 4,
        "sizes": [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 11],
        "lacing": ["single-boa"],
        "price": "245.00",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100403423-MARSHCHECK-1.png?v=1790711414",
        "notes": "The Encore OG streamlines comfort and fit through its single-dial BOA® Fit System for precise, on-the-fly adjustability anywhere you go. With a PopCush™ Footbed for advanced impact protection and a Waffle Lug Outsole for traction in all conditions, the Encore OG is built for every trail, feature, and hit you can find at the resort. With a V1 Waffle Lug outsole and classic Sidestripe™ for unmistakable Vans style, you'll look good doing it, too.",
    },
    
    # Nidecker
    {
        "name": "Rift Pro",
        "brand": "Nidecker",
        "styles": ["park", "resort"],
        "flex": 5,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13],
        "lacing": ["double-boa"],
        "price": "429.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100301491_BLK_1.png?v=1790104220",
        "notes": "A premium version of a mid-soft team favorite, the Rift Pro offers a relaxed flex that's perfect for creative riding anywhere on the mountain. The latest H5 BOA® dials provide complete control over the fit, while a Silver heat-moldable liner and 3D Pro insole ensure total comfort from day one. The sleek looks are on point too, with an upgraded KPU lower section and Armor-Tech toe that will keep your feet protected in the gnarliest of terrain.",
    },
    {
        "name": "Altai",
        "brand": "Nidecker",
        "styles": ["resort"],
        "flex": 5,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12, 13, 14],
        "lacing": ["double-boa"],
        "price": "319.95",
        "image": "",
        "notes": "The Altai is the centerpiece of our boot collection, offering premium features and support at an exceptional price. It’s built around an asymmetrical upper that minimizes pressure points, with dual H5 BOA® dials to allow you to tighten the upper and lower sections independently. The responsive, mid-stiff flex is great for digging trenches in the piste or floating through forests with pinpoint accuracy. If you love the art of the turn, you’ll love this boot.",
    },
    
    # Thirtytwo
    {
        "name": "Lashed Double BOA",
        "brand": "ThirtyTwo",
        "styles": ["all-mountain"],
        "flex": 6,
        "sizes": [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 11.5, 12],
        "lacing": ["double-boa"],
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100400989_BBG_1.png?v=1786748728",
        "notes": "The Lashed is a true hall-of-famer in the ThirtyTwo lineup. A longtime team favorite, it delivers the perfect balance of medium flex, support, and enhanced liner fit for riders who demand consistency. Add in the Performance Rubber Outsole, plush Evolution Foam cushioning, and a weather-blocking tongue cover, and you’ve got a boot built to keep you dry, comfortable, and charging from first chair to last lap.",
    },
    
    # Women's ThirtyTwo
    {
        "name": "Women's Lashed Double BOA",
        "brand": "ThirtyTwo",
        "styles": ["all-mountain"],
        "flex": 6,
        "sizes": [5, 5.5, 6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5],
        "lacing": ["double-boa"],
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100400999_MRSH_1.png?v=1786751094",
        "notes": "The Lashed Double Boa is a team favorite with well balanced medium flex, support, enhanced liner fit and the added benefit of the Dual BOA fit system featuring H5 coiler on the tongue. With Performance Rubber Outsole, Evolution Foam Cushioning and a new tongue cover to keep you dry.",
    },


]
