import json

# Union sizing chart
#
#         "sizes": [
#            {
#                "size": "S",
#                "boot_sizes": "5.5-7.5"
#            },
#            {
#                "size": "M",
#                "boot_sizes": "8-10"
#            },
#            {
#                "size": "L",
#                "boot_sizes": "10.5-13"
#            }
#          ],
#
#   Instead of creating sizing logic here in the product, I think doing its own logic and calculation based on the size is better.
#
# Format
# {
#   "gender": [],
#   "name": "",
#   "brand": "",
#   "style": [],
#   "skill": [],
#   "sizes": [
#
#   ],
#
#   "flex": ,
#   "pattern": [],
#   "type": "",
#   "price": "",
#   "image": "",
#   "notes": "."
# },
#


SB_BINDINGS = [

    # UNION BINDINGS
    # Mens Union
    {
        "gender": ["mens"],
        "name": "Source FC",
        "brand": "Union",
        "style": ["freeride", "all-mountain", "park"],
        "sizes": ["M", "L"],
        "flex": 8,
        "pattern": ["4x2"],
        "type": "traditional",
        "price": "999.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303396.FCBlack.1.png?v=1780606599",
        "notes": "The connection between rider and snowboard has never been closer. They removed the mounting disk, reduced the baseplate height, and cut hundreds of grams of excess weight. The result completely changes how your energy transfers from body to board. The Union Source FC puts you in the driver’s seat. Are you ready for the ride?",
    },
    {
        "gender": ["mens"],
        "name": "Source Pro TH",
        "brand": "Union",
        "style": ["park", "freeride", "all-mountain"],
        "sizes": ["M", "L"],
        "flex": 7,
        "pattern": ["4x2"],
        "type": "traditional",
        "price": "699.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303397.SourceProTH.Black.1.png?v=1780610364",
        "notes": "Designed with Torstein Horgmo, the all-new Union Source Pro TH blends freestyle freedom with pro-level performance. A new highback gives it a more playful, freestyle-focused feel, while cushioned Hybrid 3.0 ankle straps deliver the perfect balance of comfort, control, and response. Built for riders who want precision without restriction.",
    },
    {
        "gender": ["mens"],
        "name": "Source",
        "brand": "Union",
        "style": ["all-mountain", "park", "freeride"],
        "sizes": ["M", "L"],
        "flex": 6,
        "pattern": ["4x2"],
        "type": "traditional",
        "price": "549.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303400.Source.Black.1.png?v=1780612051",
        "notes": "The Union Source delivers a balanced ride for snowboarders who want dependable performance without the aggressive feel of the Source FC or Source Pro. A more forgiving highback, wider ankle straps, and a nylon baseplate create a setup that’s comfortable, supportive, and still keeps the close connection to the snowboard.",
    },
    {
        "gender": ["mens"],
        "name": "Atlas Pro Step On",
        "brand": "Union",
        "style": ["all-mountain", "freeride"],
        "sizes": ["M", "L", "XL"],
        "flex": 8,
        "pattern": ["4x2", "channel"],
        "type": "step-on",
        "price": "499.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303385.Black.1.png?v=1780499173",
        "notes": "Precision meets power. The Union Atlas Pro Step On® delivers all-mountain performance with the convenience of Step On® technology. An all-new highback with a forged carbon beam, paired with the new Drive Frame rear bushing, increases stiffness to deliver unmatched power and edge-to-edge response without sacrificing comfort or control.",
    },
    {
        "gender": ["mens"],
        "name": "Atlas Pro",
        "brand": "Union",
        "style": ["all-mountain", "freeride", "park"],
        "sizes": ["M","L"],
        "flex": 9,
        "pattern": ["4x2", "4x4", "channel"],
        "type": "traditional",
        "price": "499.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303401.Black.1.png?v=1780672134",
        "notes": "The Union Atlas Pro is built for riders who demand instant response and uncompromising control. Designed for intermediate to advanced snowboarders, this all-mountain powerhouse uses Italian-made Forged Carbon and Duraflex CB nylon to create a lightweight, hyper-responsive ride.The Union Atlas Pro is built for riders who demand instant response and uncompromising control. This all-mountain powerhouse uses Italian-made Forged Carbon and Duraflex CB nylon to create a lightweight, hyper-responsive ride.",
    },
    {
        "gender": ["mens"],
        "name": "Falcor",
        "brand": "Union",
        "style": ["freeride", "all-mountain", "park"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "439.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303402.Black.1.png?v=1780676964",
        "notes": "Precision engineered for Travis Rice, the Union Falcor is made for riders who push the limits of big mountain snowboarding. Lightweight, responsive, and ultra durable, it features a unique Forged Hybrid highback and Stage 12 Duraflex CB baseplate for maximum control at high speeds and on critical terrain.",
    },
    {
        "gender": ["mens"],
        "name": "Atlas Step On",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L", "XL"],
        "flex": 6,
        "pattern": ["2x4", "channel"],
        "type": "step-on",
        "price": "429.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303392.Black.1.png?v=1780506580",
        "notes": "Fast in. Fast out. Locked in for total control. The Union Atlas Step On® combines the proven convenience of Step On® technology with Union’s renowned allmountain performance. Featuring the Step On® Instant Connection™ System, this binding delivers lightning-fast entry and exit without sacrificing response, precision, or power.",
    },
    {
        "gender": ["mens"],
        "name": "Atlas",
        "brand": "Union",
        "style": ["all-mountain", "park", "freeride"],
        "sizes": ["S", "M", "L"],
        "flex": 8,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303406.Atlas.Black.1.png?v=1780693194",
        "notes": "The Union Atlas is the all-mountain binding of choice for intermediate to advanced riders who want power and precision everywhere on the mountain. With a medium-stiff flex, it delivers explosive edge-to-edge control whether you’re carving groomers, slashing powder, or charging steep lines. Designed, tested, and trusted by top riders, the Atlas performs when it matters most.",
    },
    {
        "gender": ["mens"],
        "name": "Neo",
        "brand": "Union",
        "style": ["all-mountain", "freeride"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "379.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303403.Neo.Black.1.png?v=1780680369",
        "notes": "Think outside the system. Built for riders chasing big mountain performance, the Union Neo pushes the limits of strap bindings. A dual-density bushing absorbs impact, while the three-piece baseplate adds freedom without losing response. A multi-component highback and cushioned ankle strap lock in comfort and control, setting a new standard for freeride precision.",
    },
    {
        "gender": ["mens"],
        "name": "Force Team",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["M", "L"],
        "flex": 7,
        "pattern": ["4x2", "4x4", "channel"],
        "type": "traditional",
        "price": "369.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303418.ForceTeam.Stone.1.png?v=1780701751",
        "notes": "The Union Force Team is built for riders who want more. Upgraded with pro-level components for added response, durability, and control, it’s the binding trusted by Union’s top athletes for everything from deep resort days to big mountain lines. All the dependability of the Force, dialed up to eleven.",
    },

    {
        "gender": ["mens"],
        "name": "Force",
        "brand": "Union",
        "style": ["all-mountain", "park", "freeride"],
        "sizes": ["S", "M", "L", "XL"],
        "flex": 7,
        "pattern": ["4x2", "4x4", "channel"],
        "type": "traditional",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303407.Force.Black.1.png?v=1780696910",
        "notes": "The newest generation of the Union Force delivers a smooth yet responsive ride that works for any rider, in any condition, in any terrain. More snowboarders around the globe choose to ride the Force than any other binding on the market today. Ride like the best—ride the Force.",
    },
    {
        "gender": ["mens"],
        "name": "Ultra",
        "brand": "Union",
        "style": ["freeride"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x2", "channel"],
        "type": "",
        "price": "329.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303409.Black.1.png?v=1780948051",
        "notes": "Strap into the most comfortable snowboard binding ever built. The Union Ultra redefines board feel with a next generation suspension system that flexes, rebounds, and absorbs impact with every move. From baseplate to straps, every part works together to deliver a smooth, cushioned ride. The Ultra is snowboarding evolved.",
    },
    {
        "gender": ["mens"],
        "name": "Strata",
        "brand": "Union",
        "style": ["park", "all-mountain"],
        "sizes": ["S","M","L"],
        "flex": ,
        "pattern": [],
        "type": "traditional",
        "price": "279.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303410.Black.1.png?v=1780954286",
        "notes": "Union’s #1 men’s park and freestyle binding. The Strata is built for riders who want to press, pop, and play across the entire mountain. With a soft, surfy flex and industry-leading shock absorption, it delivers a buttery ride that doesn't compromise on control.",
    },
    {
        "gender": ["mens"],
        "name": "Force Classic",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "249.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100258669-BLK-1.png?v=1688145802",
        "notes": "Union's most iconic and best-selling binding model of all time. The Union Force Classic is a bombproof, all mountain snowboard binding designed to do it all. With minimal changes from season to season, the Force Classic is here to stay.",
    },
    {
        "gender": ["mens"],
        "name": "Contact",
        "brand": "Union",
        "style": ["park"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "229.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303411.Contact.Black.1_11b23dd7-d8cf-41a7-bc3e-fa24b3b5bd43.png?v=1780958596",
        "notes": "The Union Contact is back. Lightweight, surfy, and built for park laps, side hits, and creative freestyle riding across the mountain. With a soft, asymmetric highback and minimal board-to-binding contact, it delivers a true skate-like feel. Dial in your setup and let your style do the talking.",
    },
    {
        "gender": ["mens"],
        "name": "STR",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "tradtional",
        "price": "199.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303408.STR.Black.1.png?v=1780704023",
        "notes": "Comfort, control, and confidence right out of the box. The Union STR is a durable, mid-flexing all-mountain binding made for riders who want to level up. With all-day comfort and a forgiving response, it’s perfect for beginner to intermediate snowboarders who want to explore more of the mountain with every run.",
    },
    {
        "gender": ["mens"],
        "name": "Flite Pro",
        "brand": "Union",
        "style": ["park"],
        "sizes": ["S", "M", "L"],
        "flex": 4,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "169.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100292094_BLK_1.png?v=1750281705",
        "notes": "Strap in to the lightest men's snowboard binding on the market. The Union Flite Pro is a lightweight, soft-flexing, freestyle snowboard binding for beginner to intermediate snowboarders. Perfect for learning to ride the entire mountain or taking your first park laps.",
    },
    
    
    # Womens Union
    {
        "gender": ["Women's"],
        "name": "Women's Astra Step On",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x2", "channel"],
        "type": "step-on",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303412.WsAstraStepOn.Black.1_37e9eb21-0918-44dc-ab11-71298dd83785.png?v=1780961154",
        "notes": "Fast in. Fast out. Locked in for total control. The Union Astra Step On® brings the proven convenience of Step On® technology to women’s all-mountain performance. Featuring the Step On® Instant Connection™ System, the Astra delivers lightning-fast entry and exit without sacrificing response, precision, or power.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Trilogy",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303413.White.1.png?v=1781018384",
        "notes": "Built for the next generation of women snowboarders, the Union Trilogy provides a smooth, comfortable ride that works in any condition and on any terrain. More women choose the Trilogy than any other binding on the market. Ride like Mia—ride the Trilogy.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Ultra",
        "brand": "Union",
        "style": ["freestyle"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "329.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303415.WsUltra.Black.1.png?v=1781029161",
        "notes": "Strap into the most comfortable snowboard binding ever built. The Union Ultra redefines board feel with a next-generation suspension system that flexes, rebounds, and absorbs impact with every move. From baseplate to straps, every part works together to deliver a smooth, cushioned ride. The Ultra is snowboarding evolved.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Legacy",
        "brand": "Union",
        "style": ["freestyle"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "279.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303416.WsLegacy.White.1.png?v=1781035216",
        "notes": "Union’s #1 women’s park and freestyle binding. The Legacy has a soft, surfy feel with next-level shock absorption for riders who love lapping the park, pressing rails, and carving creative lines. Lightweight, responsive, and built to last, the Legacy is a fan favorite for good reason.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Contact",
        "brand": "Union",
        "style": ["freestyle"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "229.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303417.WsContact.Violet.1.png?v=1781038077",
        "notes": "For the first time, the Union Contact is also built for women. Lightweight, surfy, and built for park laps, side hits, and creative freestyle riding across the mountain. With a soft, asymmetric highback and minimal board-to-binding contact, it delivers a true skate-like feel. Dial in your setup and let your style do the talking.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Juliet",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "199.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303414.Juliet.Black.1.png?v=1781024643",
        "notes": "All-day comfort, all-mountain versatility. The Union Juliet is a durable, mid-flexing women’s binding built for beginner to intermediate riders ready to explore more of the mountain. With a smooth, responsive ride and a women’s-specific fit, the Juliet delivers the support you need to progress with confidence.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Rosa",
        "brand": "Union",
        "style": ["park"],
        "sizes": ["S", "M", "L"],
        "flex": 4,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "199.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100292099_BLK_1.png?v=1754107241",
        "notes": "Strap in to the lightest women's snowboard binding on the market. The Union Rosa is a lightweight, soft-flexing, freestyle snowboard binding for beginner to intermediate snowboarders. Perfect for learning to ride the entire mountain or taking your first park laps."
    },

    # Burton
    {
        "gender": [],
        "name": "",
        "brand": "",
        "style": [],
        "sizes": [],
        "flex": ,
        "pattern": [""],
        "type": "",
        "price": "",
        "image": "",
        "notes": ""
    },

]
