import json

# Union sizing chart
#
#         "sizes": [
#            {
#                "size": "S",
#                "boot_sizes": "5.5-7.5"
#            },
#            {
#                "size": "M",
#                "boot_sizes": "8-10"
#            },
#            {
#                "size": "L",
#                "boot_sizes": "10.5-13"
#            }
#          ],
#
#   Instead of creating sizing logic here in the product, I think doing its own logic and calculation based on the size is better.
#
# Format
# {
#   "gender": [],
#   "name": "",
#   "brand": "",
#   "style": [],
#   "skill": [],
#   "sizes": [
#
#   ],
#
#   "flex": ,
#   "pattern": [],
#   "type": "",
#   "price": "",
#   "image": "",
#   "notes": "."
# },
#


SB_BINDINGS = [

    # UNION BINDINGS
    # Mens Union
    {
        "gender": ["mens"],
        "name": "Source FC",
        "brand": "Union",
        "style": ["freeride", "all-mountain", "park"],
        "sizes": ["M", "L"],
        "flex": 8,
        "pattern": ["4x2"],
        "type": "traditional",
        "price": "999.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303396.FCBlack.1.png?v=1780606599",
        "notes": "The connection between rider and snowboard has never been closer. They removed the mounting disk, reduced the baseplate height, and cut hundreds of grams of excess weight. The result completely changes how your energy transfers from body to board. The Union Source FC puts you in the driver’s seat. Are you ready for the ride?",
    },
    {
        "gender": ["mens"],
        "name": "Source Pro TH",
        "brand": "Union",
        "style": ["park", "freeride", "all-mountain"],
        "sizes": ["M", "L"],
        "flex": 7,
        "pattern": ["4x2"],
        "type": "traditional",
        "price": "699.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303397.SourceProTH.Black.1.png?v=1780610364",
        "notes": "Designed with Torstein Horgmo, the all-new Union Source Pro TH blends freestyle freedom with pro-level performance. A new highback gives it a more playful, freestyle-focused feel, while cushioned Hybrid 3.0 ankle straps deliver the perfect balance of comfort, control, and response. Built for riders who want precision without restriction.",
    },
    {
        "gender": ["mens"],
        "name": "Source",
        "brand": "Union",
        "style": ["all-mountain", "park", "freeride"],
        "sizes": ["M", "L"],
        "flex": 6,
        "pattern": ["4x2"],
        "type": "traditional",
        "price": "549.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303400.Source.Black.1.png?v=1780612051",
        "notes": "The Union Source delivers a balanced ride for snowboarders who want dependable performance without the aggressive feel of the Source FC or Source Pro. A more forgiving highback, wider ankle straps, and a nylon baseplate create a setup that’s comfortable, supportive, and still keeps the close connection to the snowboard.",
    },
    {
        "gender": ["mens"],
        "name": "Atlas Pro Step On",
        "brand": "Union",
        "style": ["all-mountain", "freeride"],
        "sizes": ["M", "L", "XL"],
        "flex": 8,
        "pattern": ["4x2", "channel"],
        "type": "step-on",
        "price": "499.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303385.Black.1.png?v=1780499173",
        "notes": "Precision meets power. The Union Atlas Pro Step On® delivers all-mountain performance with the convenience of Step On® technology. An all-new highback with a forged carbon beam, paired with the new Drive Frame rear bushing, increases stiffness to deliver unmatched power and edge-to-edge response without sacrificing comfort or control.",
    },
    {
        "gender": ["mens"],
        "name": "Atlas Pro",
        "brand": "Union",
        "style": ["all-mountain", "freeride", "park"],
        "sizes": ["M","L"],
        "flex": 9,
        "pattern": ["4x2", "4x4", "channel"],
        "type": "traditional",
        "price": "499.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303401.Black.1.png?v=1780672134",
        "notes": "The Union Atlas Pro is built for riders who demand instant response and uncompromising control. Designed for intermediate to advanced snowboarders, this all-mountain powerhouse uses Italian-made Forged Carbon and Duraflex CB nylon to create a lightweight, hyper-responsive ride.The Union Atlas Pro is built for riders who demand instant response and uncompromising control. This all-mountain powerhouse uses Italian-made Forged Carbon and Duraflex CB nylon to create a lightweight, hyper-responsive ride.",
    },
    {
        "gender": ["mens"],
        "name": "Falcor",
        "brand": "Union",
        "style": ["freeride", "all-mountain", "park"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "439.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303402.Black.1.png?v=1780676964",
        "notes": "Precision engineered for Travis Rice, the Union Falcor is made for riders who push the limits of big mountain snowboarding. Lightweight, responsive, and ultra durable, it features a unique Forged Hybrid highback and Stage 12 Duraflex CB baseplate for maximum control at high speeds and on critical terrain.",
    },
    {
        "gender": ["mens"],
        "name": "Atlas Step On",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L", "XL"],
        "flex": 6,
        "pattern": ["2x4", "channel"],
        "type": "step-on",
        "price": "429.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303392.Black.1.png?v=1780506580",
        "notes": "Fast in. Fast out. Locked in for total control. The Union Atlas Step On® combines the proven convenience of Step On® technology with Union’s renowned allmountain performance. Featuring the Step On® Instant Connection™ System, this binding delivers lightning-fast entry and exit without sacrificing response, precision, or power.",
    },
    {
        "gender": ["mens"],
        "name": "Atlas",
        "brand": "Union",
        "style": ["all-mountain", "park", "freeride"],
        "sizes": ["S", "M", "L"],
        "flex": 8,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303406.Atlas.Black.1.png?v=1780693194",
        "notes": "The Union Atlas is the all-mountain binding of choice for intermediate to advanced riders who want power and precision everywhere on the mountain. With a medium-stiff flex, it delivers explosive edge-to-edge control whether you’re carving groomers, slashing powder, or charging steep lines. Designed, tested, and trusted by top riders, the Atlas performs when it matters most.",
    },
    {
        "gender": ["mens"],
        "name": "Neo",
        "brand": "Union",
        "style": ["all-mountain", "freeride"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "379.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303403.Neo.Black.1.png?v=1780680369",
        "notes": "Think outside the system. Built for riders chasing big mountain performance, the Union Neo pushes the limits of strap bindings. A dual-density bushing absorbs impact, while the three-piece baseplate adds freedom without losing response. A multi-component highback and cushioned ankle strap lock in comfort and control, setting a new standard for freeride precision.",
    },
    {
        "gender": ["mens"],
        "name": "Force Team",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["M", "L"],
        "flex": 7,
        "pattern": ["4x2", "4x4", "channel"],
        "type": "traditional",
        "price": "369.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303418.ForceTeam.Stone.1.png?v=1780701751",
        "notes": "The Union Force Team is built for riders who want more. Upgraded with pro-level components for added response, durability, and control, it’s the binding trusted by Union’s top athletes for everything from deep resort days to big mountain lines. All the dependability of the Force, dialed up to eleven.",
    },

    {
        "gender": ["mens"],
        "name": "Force",
        "brand": "Union",
        "style": ["all-mountain", "park", "freeride"],
        "sizes": ["S", "M", "L", "XL"],
        "flex": 7,
        "pattern": ["4x2", "4x4", "channel"],
        "type": "traditional",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303407.Force.Black.1.png?v=1780696910",
        "notes": "The newest generation of the Union Force delivers a smooth yet responsive ride that works for any rider, in any condition, in any terrain. More snowboarders around the globe choose to ride the Force than any other binding on the market today. Ride like the best—ride the Force.",
    },
    {
        "gender": ["mens"],
        "name": "Ultra",
        "brand": "Union",
        "style": ["freeride"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x2", "channel"],
        "type": "",
        "price": "329.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303409.Black.1.png?v=1780948051",
        "notes": "Strap into the most comfortable snowboard binding ever built. The Union Ultra redefines board feel with a next generation suspension system that flexes, rebounds, and absorbs impact with every move. From baseplate to straps, every part works together to deliver a smooth, cushioned ride. The Ultra is snowboarding evolved.",
    },
    {
        "gender": ["mens"],
        "name": "Strata",
        "brand": "Union",
        "style": ["park", "all-mountain"],
        "sizes": ["S","M","L"],
        "flex": ,
        "pattern": [],
        "type": "traditional",
        "price": "279.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303410.Black.1.png?v=1780954286",
        "notes": "Union’s #1 men’s park and freestyle binding. The Strata is built for riders who want to press, pop, and play across the entire mountain. With a soft, surfy flex and industry-leading shock absorption, it delivers a buttery ride that doesn't compromise on control.",
    },
    {
        "gender": ["mens"],
        "name": "Force Classic",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "249.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100258669-BLK-1.png?v=1688145802",
        "notes": "Union's most iconic and best-selling binding model of all time. The Union Force Classic is a bombproof, all mountain snowboard binding designed to do it all. With minimal changes from season to season, the Force Classic is here to stay.",
    },
    {
        "gender": ["mens"],
        "name": "Contact",
        "brand": "Union",
        "style": ["park"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "229.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303411.Contact.Black.1_11b23dd7-d8cf-41a7-bc3e-fa24b3b5bd43.png?v=1780958596",
        "notes": "The Union Contact is back. Lightweight, surfy, and built for park laps, side hits, and creative freestyle riding across the mountain. With a soft, asymmetric highback and minimal board-to-binding contact, it delivers a true skate-like feel. Dial in your setup and let your style do the talking.",
    },
    {
        "gender": ["mens"],
        "name": "STR",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "tradtional",
        "price": "199.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303408.STR.Black.1.png?v=1780704023",
        "notes": "Comfort, control, and confidence right out of the box. The Union STR is a durable, mid-flexing all-mountain binding made for riders who want to level up. With all-day comfort and a forgiving response, it’s perfect for beginner to intermediate snowboarders who want to explore more of the mountain with every run.",
    },
    {
        "gender": ["mens"],
        "name": "Flite Pro",
        "brand": "Union",
        "style": ["park"],
        "sizes": ["S", "M", "L"],
        "flex": 4,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "169.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100292094_BLK_1.png?v=1750281705",
        "notes": "Strap in to the lightest men's snowboard binding on the market. The Union Flite Pro is a lightweight, soft-flexing, freestyle snowboard binding for beginner to intermediate snowboarders. Perfect for learning to ride the entire mountain or taking your first park laps.",
    },
    
    
    # Womens Union
    {
        "gender": ["Women's"],
        "name": "Women's Astra Step On",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x2", "channel"],
        "type": "step-on",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303412.WsAstraStepOn.Black.1_37e9eb21-0918-44dc-ab11-71298dd83785.png?v=1780961154",
        "notes": "Fast in. Fast out. Locked in for total control. The Union Astra Step On® brings the proven convenience of Step On® technology to women’s all-mountain performance. Featuring the Step On® Instant Connection™ System, the Astra delivers lightning-fast entry and exit without sacrificing response, precision, or power.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Trilogy",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303413.White.1.png?v=1781018384",
        "notes": "Built for the next generation of women snowboarders, the Union Trilogy provides a smooth, comfortable ride that works in any condition and on any terrain. More women choose the Trilogy than any other binding on the market. Ride like Mia—ride the Trilogy.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Ultra",
        "brand": "Union",
        "style": ["freestyle"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "329.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303415.WsUltra.Black.1.png?v=1781029161",
        "notes": "Strap into the most comfortable snowboard binding ever built. The Union Ultra redefines board feel with a next-generation suspension system that flexes, rebounds, and absorbs impact with every move. From baseplate to straps, every part works together to deliver a smooth, cushioned ride. The Ultra is snowboarding evolved.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Legacy",
        "brand": "Union",
        "style": ["freestyle"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "279.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303416.WsLegacy.White.1.png?v=1781035216",
        "notes": "Union’s #1 women’s park and freestyle binding. The Legacy has a soft, surfy feel with next-level shock absorption for riders who love lapping the park, pressing rails, and carving creative lines. Lightweight, responsive, and built to last, the Legacy is a fan favorite for good reason.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Contact",
        "brand": "Union",
        "style": ["freestyle"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x2", "channel"],
        "type": "traditional",
        "price": "229.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303417.WsContact.Violet.1.png?v=1781038077",
        "notes": "For the first time, the Union Contact is also built for women. Lightweight, surfy, and built for park laps, side hits, and creative freestyle riding across the mountain. With a soft, asymmetric highback and minimal board-to-binding contact, it delivers a true skate-like feel. Dial in your setup and let your style do the talking.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Juliet",
        "brand": "Union",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "199.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100303414.Juliet.Black.1.png?v=1781024643",
        "notes": "All-day comfort, all-mountain versatility. The Union Juliet is a durable, mid-flexing women’s binding built for beginner to intermediate riders ready to explore more of the mountain. With a smooth, responsive ride and a women’s-specific fit, the Juliet delivers the support you need to progress with confidence.",
    },
    {
        "gender": ["Women's"],
        "name": "Women's Rosa",
        "brand": "Union",
        "style": ["park"],
        "sizes": ["S", "M", "L"],
        "flex": 4,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "199.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100292099_BLK_1.png?v=1754107241",
        "notes": "Strap in to the lightest women's snowboard binding on the market. The Union Rosa is a lightweight, soft-flexing, freestyle snowboard binding for beginner to intermediate snowboarders. Perfect for learning to ride the entire mountain or taking your first park laps."
    },

    # Burton
    {
        "gender": ["mens"],
        "name": "Step On X Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 8,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "step-on",
        "price": "479.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304037_BLK_1.png?v=1781567875",
        "notes": "The men's Step On® X Bindings pair the instant connection of Step On® with the pro-caliber control of a carbon-blend hi-back and baseplate. The combination makes for an extra-responsive ride that lets you charge across the entire mountain with confidence. Heel Grabber technology provides the ultimate connection between the baseplate and the hi back, increasing response when going heel to toe."
    },
    {
        "gender": ["mens"],
        "name": "Step On Genesis Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L", "XL"],
        "flex": 6,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "step-on",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304039_BLK_1.png?v=1781570476",
        "notes": "Supercharge your suspension for a responsive ride with the men's Burton Step On® Genesis Snowboard Bindings. They cradle your heel in complete suspension for increased response and reduced vibration. Maximum cushioning and the instant connection of Step On® make for playful bindings that have you riding longer."
    },
    {
        "gender": ["mens"],
        "name": "Step On Genesis EST",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L", "XL"],
        "flex": 6,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "step-on",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304038_BLK_1.png?v=1781569706",
        "notes": "The men's Burton Step On® Genesis EST Snowboard Bindings bring the instant connection of Step On® to the team-rider-proven power of the Genesis. They combine the plush cushioning of EST with a baseplate that maintains natural medial/lateral movement for less fatigue and easier ollies. Compatible with boards featuring The Channel® mounting system for the ultimate in flex, feel, and adjustability."
    },
    {
        "gender": ["mens"],
        "name": "Malavita X",
        "brand": "Burton",
        "style": ["park"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304045_BKWH_1.png?v=1781745341",
        "notes": "The men's Burton Malavita X Snowboard Bindings has the ability to handle any terrain on the mountain with smooth, high-end performance. The low-profile design and straps work together to create a gapless, boot-hugging connection that gives you the control you need to push your riding."
    },
    {
        "gender": ["mens"],
        "name": "Cartel X Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 8,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100210484_BLK_1.png?v=1740083151",
        "notes": "Experience comfort and response in the men's Burton Cartel X Re:Flex Snowboard Binding. This shred-it-all binding offers top features like a Hammock ankle strap and Heel Hammock hi-back for enhanced hold and response. The FullBED cushioning sets a high standard for comfort, while freestyle-minded zero forward lean lets dial in your stance. The Re:Flex version is compatible with any board mounting system."
    },
    {
        "gender": ["mens"],
        "name": "Step On Cartel X EST",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 8,
        "pattern": [""],
        "type": "step-on",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304040_BLK_1.png?v=1781720226",
        "notes": "The Cartel X EST Step On® stacks three things that each make you ride better: the versatility of Burton's best-selling binding, the direct board feel of EST's limited-hardware design, and the instant connection of Step On®. You feel more of what your board's doing, get back in line faster, and stay out longer with SensoryBED cushioning. This binding eliminates the obstacles between you and the ride. Channel boards only."
    },
    {
        "gender": ["mens"],
        "name": "Step On Cartel X",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["channel"],
        "type": "step-on",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304041_BLK_1.png?v=1781721926",
        "notes": "The Cartel X Step On® combines Burton’s best-selling binding with the speed and response of Step On®. Instant connection means you're already riding before anyone else has strapped in. The responsive flex and direct boot-to-binding interface give you immediate edge control to push into park laps, groomers, or powder with confidence. FullBED cushioning keeps things comfortable for long days on snow, so you can keep stacking runs. For riders who want everything: the versatility of Cartel X with the performance and response of Step On®."
    },
    {
        "gender": ["mens"],
        "name": "Cartel X EST",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 8,
        "pattern": ["channel"],
        "type": "traditional",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100210483_BLK_1.png?v=1740083149",
        "notes": "Experience comfort and response in the men's Burton Cartel X EST® Snowboard Binding. This shred-it-all binding offers top features like a Hammock ankle strap and Heel Hammock hi-back for enhanced hold and response. The SensoryBED cushioning sets a high standard for feel and control, while freestyle-minded zero forward lean lets dial in your stance. The EST® version is only compatible with Burton's Channel® board mounting system and offers the ultimate in flex, feel, and adjustability."
    },
    {
        "gender": ["mens"],
        "name": "Step On Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L", "XL"],
        "flex": 5,
        "pattern": ["channel", "4x2", "4x4"],
        "type": "step-on",
        "price": "319.95",
        "image": "https://www.sportsbasement.com/cdn/shop/products/100221508_BLK_2.png?v=1743705435",
        "notes": "The Burton Step On Re:Flex Snowboard Binding offers an intuitive boot to binding connection for riders seeking both convenience and performance. Three connection points – two by the toe and one at the heel – deliver unmatched simplicity, security, and board control, while a quick-release lever ensures quick and easy exit. Universally compatible with all current snowboard mounting systems, including 4x4, 3D®, and The Channel®."
    },
    {
        "gender": ["mens"],
        "name": "Cartel Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "299.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100210482_SSNK_1.png?v=1781191822",
        "notes": "Standing the test of time takes more than durability, it requires evolving. The men's Burton Cartel Snowboard Bindings bring updated strap and buckle tech to make sure the blend of comfort and control continues to deliver the versatility that put it on the map. Full days on your board are better with full underfoot cushioning to reduce fatigue and add comfort. Re:Flex baseplates are universally compatible with all major mounting systems. "
    },
    {
        "gender": ["mens"],
        "name": "Malavita",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "299.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304046_BLKF_1.png?v=1782154517",
        "notes": "Serving up professional-grade reliability, the Burton Malavita Snowboard Bindings are a true workhorse. These do-it-all bindings have a low profile and plenty of cushioning so you get the foot-hugging comfort you need to ride all types of terrain all over the mountain."
    },
    
    # Womens Burton
    {
        "gender": ["womens"],
        "name": "Women's Step On Escapade EST",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["channel"],
        "type": "step-on",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304042_PVLT_1.png?v=1781740106",
        "notes": "The women's Step On® Escapade EST Bindings bring the instant connection of Step On® to the team-rider-proven power of the Escapade. They combine the plush cushioning of EST with a baseplate that maintains natural medial/lateral movement for less fatigue and easier ollies. Compatible with boards featuring The Channel® mounting system for the ultimate in flex, feel, and adjustability."
    },
    {
        "gender": ["womens"],
        "name": "Women's Lexa X Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100269701_BLK_1.png?v=1740083061",
        "notes": "A legendary blend of comfort and all-terrain versatility updated for even lighter, more responsive performance. The women's Burton Lexa X Re:Flex Snowboard Bindings are a shred-it-all binding made for pro-caliber control. From the responsive hi-back and freestyle-minded zero forward lean, the Re:Flex edition is loaded with comfort-driven performance features to keep you pushing your skill and riding longer."
    },
    {
        "gender": ["womens"],
        "name": "Women's Step On Lexa X EST",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["channel"],
        "type": "step-on",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304043_BLK_1.png?v=1781742254",
        "notes": "The Lexa X EST Step On® gives you three things at once: the enhanced underfoot flex of EST, the all-day comfort of SensoryBED cushioning, and the performance of Step On®. You’ll feel more of what your board's doing, unlocking new levels of precision in every turn you make. And you'll be taking more runs too, because you're not burning time at the top of every run. That's how you progress faster. Channel boards only."
    },
    {
        "gender": ["womens"],
        "name": "Women's Step On Lexa X",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 7,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "step-on",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100304044_BLK_1.png?v=1781743803",
        "notes": "A legendary blend of comfort and all-terrain versatility updated for even lighter, more responsive performance. The women's Burton Lexa X Step On® Snowboard Bindings are shred-it-all bindings made for pro-caliber control. The Re:Flex edition is loaded with comfort-driven performance features to keep you pushing your skills and riding longer. Just step on and ride."
    },
    {
        "gender": ["womens"],
        "name": "Women's Step On Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "step-on",
        "price": "319.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100221506_MNDP_1.png?v=1781195314",
        "notes": "The women's Burton Step On Binding offers the most intuitive boot to binding connection for riders seeking both convenience and performance. Three connection points – two by the toe and one at the heel – deliver unmatched simplicity, security, and board control, while a quick release lever ensures quick and easy exit. Universally compatible with all current snowboard mounting systems, including 4x4, 3D®, and The Channel®."
    },
    {
        "gender": ["womens"],
        "name": "Women's Lexa Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "traditional",
        "price": "299.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100269702_MNDP_1.png?v=1781199154",
        "notes": "Standing the test of time takes more than durability, it requires evolving, too. The women's Burton Lexa Re:Flex Snowboard Bindings bring across-the-board compatibility of Re:Flex plus the latest strap and buckle tech to make sure the Lexa's blend of comfort and control continues to deliver the versatility that put it on the map. Days on your board are better with full underfoot cushioning to reduce fatigue and add comfort."
    },
    {
        "gender": ["womens"],
        "name": "Women's Scribe Re:Flex",
        "brand": "Burton",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 4,
        "pattern": ["4x2", "4x4", "channel"],
        "type": "traditional",
        "price": "249.95",
        "image": "https://www.sportsbasement.com/cdn/shop/products/10552108001_1.png?v=1743636707",
        "notes": "Offering a multi-talented package for all-terrain fun, the women's Burton Scribe Re:Flex Snowboard Bindings remain soft, flexible and responsive no matter your riding style. Sitting at the sweet spot between power and playfulness, a canted The Hinge hi-back dials in response, while the comfort-centric straps deliver a smooth, surefooted ride. The Scribe's cloud-like cushioning softens every inch of the mountain. The Re:Flex mounting plate offers across-the-board compatibility with all major mounting systems."
    },
    
    # Bataleon
    {
        "gender": ["mens"],
        "name": "Blaster PRO AW FASE",
        "brand": "Bataleon",
        "style": ["all-mountain"],
        "sizes": ["M/L", "L/XL"],
        "flex": 7,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "fase",
        "price": "399.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100309167_TORG_1.png?v=1780939288",
        "notes": "The Blaster Pro AsymWrap™ FASE® Binding is Bataleon's most high-performance fast-entry binding. In collaboration with Tor Lundström, we took the FASE® Blaster and leveled it up. Now with a Carbon Infused Baseplate and a Fiberglass-injected Highback, this binding yearns for big terrain. Lighter, stiffer, with a sick graphic - what more could you ask for?"
    },
    {
        "gender": ["mens"],
        "name": "Blaster AW FASE",
        "brand": "Bataleon",
        "style": ["all-mountain"],
        "sizes": ["S","M/L", "L/XL"],
        "flex": 6,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "fase",
        "price": "379.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100309168_BLK_1.png?v=1780939287",
        "notes": "The Men's Blaster AsymWrap™ FASE® is the flagship fast-entry, high-performance binding in the Bataleon collection. All the components you know and love about Blaster, and the added FASE® Technology - served up with the Bataleon flavor. Mix together the iconic AsymWrap™ Chassis for flexibility for tweaks, the 2º Canted Footbed for ergonomic comfort, and the signature boot-wrap of AuxTech® straps, and you'll be riding from open to close in this binding."
    },
    {
        "gender": ["mens"],
        "name": "Ghost FASE",
        "brand": "Bataleon",
        "style": ["all-mountain"],
        "sizes": ["XS", "S", "M", "L"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "fase",
        "price": "299.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100309169_BLK_1.png?v=1780944193",
        "notes": "Introducing the NEW! 2627 Men's Ghost FASE® Snowboard Binding - Bataleon's latest collaboration with our friends at the FASE® brand. Progression and innovation are key pillars of our brand, and the Ghost binding is both the proof and the result. Our engineers developed the MonoFrame™ chassis to create unrivaled control while allowing the board to flex naturally underfoot - ultimately creating a comfortable Direct Connection to your snowboard. A premium strap package is added to this binding to give riders the ultimate all-mountain, freestyle binding - with the most modern technology."
    },
    
    # Womens Bataleon Bindings
    {
        "gender": ["womens"],
        "name": "Women's Blaster AW FASE",
        "brand": "Bataleon",
        "style": ["all-mountain"],
        "sizes": ["S", "M/L"],
        "flex": 6,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "fase",
        "price": "379.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100309171_MGRY_1.png?v=1780941873",
        "notes": "A versatile all-mountain binding designed for riders who demand precision and comfort in every turn. Featuring the innovative FASE® Fast Entry System, this binding allows for effortless and intuitive strapping in, so you can seamlessly transition from the lift to the slopes. The asymmetrical lightweight aluminum frame enhances side-to-side flex, providing a dynamic ride that adapts to any terrain, from park features to backcountry adventures. With the 3D AuxTech® Cradle FastStraps, you’ll enjoy an exceptional locked-in fit and responsiveness."
    },
    {
        "gender": ["womens"],
        "name": "Women's Ghost FASE",
        "brand": "Bataleon",
        "style": ["all-mountain"],
        "sizes": ["XS", "S", "M"],
        "flex": 5,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "fase",
        "price": "299.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100309172_GRYP_1.png?v=1780956286",
        "notes": "Introducing the NEW! 2627 Women's Ghost FASE® Snowboard Binding - Bataleon's latest addition to the collection in collaboration with our friends at FASE®. Progression and innovation are key pillars of our brand, and the Ghost binding is both the proof and the result. We've developed the MonoFrame™ chassis to create outstanding control while allowing the board to flex naturally underfoot - ultimately creating a comfortable Direct Connection to your snowboard. A premium strap package is added to this binding to give riders the ultimate all-mountain, freestyle binding - with the most modern technology."
    },
    
    # Jones
    {
        "gender": ["womens", "mens"],
        "name": "Mercury FASE",
        "brand": "Jones",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 8,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "fase",
        "price": "369.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100291913.EclipseBlack.1.png?v=1766525573",
        "notes": "The Mercury FASE® binding is a next-gen all-mountain freeride binding that offers the locked-in board feel, all-day comfort, and precise response of a traditional two-strap binding combined with the FASE® Fast Entry System. The Fusion XR Baseplate delivers dynamic power and response with active impact cushioning. It’s made for confident riders who shred in all conditions and terrain."
    },
    {
        "gender": ["womens", "mens"],
        "name": "Nebula FASE",
        "brand": "Jones",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 4,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "fase",
        "price": "299.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100308731_CWHT_1.png?v=1780069215",
        "notes": "The Nebula FASE® is a next-gen all-mountain freestyle binding offering playful response and all-day comfort. The responsive D-Fuse XR Baseplate cushions impacts, while the tweak-friendly highback and ankle strap unlock creative mountain surfing. With the natural feel of a two-strap binding and the FASE® Fast Entry System, it’s made for riders who turn the whole mountain into their playground."
    },
    {
        "gender": ["womens", "mens"],
        "name": "LT Supermatic",
        "brand": "Nidecker",
        "style": ["all-mountain"],
        "sizes": ["M", "L", "XL"],
        "flex": 8,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "supermatic",
        "price": "479.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100291942_BLK_1.png?v=1790098889",
        "notes": "The next chapter in speed entry. LT Supermatic® pairs revolutionary convenience with a streamlined asymmetric highback and low-mass strap design. Enjoy increased drive through turns, sharper edge response and a flex level that’s right in the sweet spot for resort ripping or park lapping. LSR 2.0 ratchets automatically lock in your strap settings, while the upgraded toestrap features enhanced 3D shaping for a precision fit."
    },
    {
        "gender": ["womens", "mens"],
        "name": "OG Supermatic",
        "brand": "Nidecker",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L", "XL"],
        "flex": 6,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "supermatic",
        "price": "429.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100287656_BLK_1.png?v=1790091978",
        "notes": "The OG Supermatic® is an original game changer – a hands-free fast entry binding that works with virtually any boot. Just push your foot in through the back and step down on the heel pedal to flip up the hiback. That’s it – you’re ready to shred. A simple release lever makes exiting just as rapid. Supermatic® feels just like a classic two-strap binding to ride, and you can even operate the ratchets normally if the conditions demand it. Steep slope? Deep pow? No problem."
    },
    {
        "gender": ["mens"],
        "name": "T32M Fava FASE",
        "brand": "ThirtyTwo",
        "style": ["all-mountain"],
        "sizes": ["S", "M", "L"],
        "flex": 6,
        "pattern": ["4x4", "4x2", "channel"],
        "type": "supermatic",
        "price": "349.95",
        "image": "https://www.sportsbasement.com/cdn/shop/files/100400969_FWHT_1.png?v=1786744556",
        "notes": "Engineered to own every line, the T32M FASE® binding locks you in from pow to park. With unrivaled support, mind-bending flex and uncompromising durability, it's built for the ultimate ride... every single time. As for boot-to-binding connection? Meet your new teammate."
    }
]
